Source/Common/Networking.cs
Source/Common/ServerConnection.cs

Fixed the changed selection maximum and an off-by-one error in a helper function

Wip 1.1 handle selection fix

---

Source/Client/Sync/SyncHandlers.cs

Can be reproduced in:
[quest-build-monument.zip](https://github.com/rwmt/Multiplayer/files/4434740/quest-build-monument.zip)

Sync 'Build Monument' quest's MonumentMarker gui

---

Source/Client/Sync/SyncHandlers.cs

eg. On a Pod Launcher or a Passive Cooler

Sync 'Toggle Automatic Refuel'

---

Source/Client/ClientConnection.cs

Fixes the recent "Stuck on Connecting window" error reports

Fix null exception introduced by Auto Reconnect after Mods Sync

---

About/Manifest.xml
workshop_bundler.sh

Also remove dependency info from Manifest.xml, Fluffy can also use Vanilla's About.xml, so lets have 1 source of truth.

workshop_bundler.sh: update Fluffy mod manager's manifest.xml

---

Source/Client/Comp/MapAsyncTime.cs

Quests that trigger a Raid currently send 2-3x more enemies in MP than with the mod off.
[1h-before-raid-quest-arrives.zip](https://github.com/rwmt/Multiplayer/files/4498684/1h-before-raid-quest-arrives.zip)
This fix is an expansion of an existing patch (that presumably was sufficient for 1.0, but 1.1's evidently refactored how quests are triggered a bit) for `StoryTeller.AllIncidentTargets`, that aims to limit which Quest Parts are iterated over in StorytellerTick() to just those which pertain to the current map being ticked, as the MP mod seems to tick for the World and then each Map individually.

Fixed Raid Quests being re-triggered per tick, tripling raid size

---

Languages/German/Keyed/Multiplayer.xml

Added missing tokens, translated missing lines, and completely overhauled existing translation to improve localization quality.
I made sure to bring it on-par with the English translation file to include all the excact same tokens, and have them localized properly.

Updated German language

---

Source/Client/SaveLoad.cs

Autosaves abruptly starting a new music track sux.
I was hoping to also restore open Windows during an autosave, but my efforts seem to get them stuck in a weird open state, where closing them spams the "window closed" noise until you reopen it. WIP: https://github.com/rwmt/Multiplayer/commit/4f6fe707e2b71401626a30d8e5d87c13b998e28b

Resume same music track after autosave

---

Source/Client/Sync/SyncDictionary.cs
Source/Client/Sync/SyncHandlers.cs

Tweak of #82 with a SyncWorker added

Sync 'Give Speech' button

---

Languages/English/Keyed/Multiplayer.xml
Languages/German/Keyed/Multiplayer.xml
Source/Client/ClientNetworking.cs
Source/Client/Comp/MapAsyncTime.cs
Source/Client/Comp/MultiplayerAsyncQuest.cs
Source/Client/Comp/MultiplayerWorldComp.cs
Source/Client/DebugActions.cs
Source/Client/Desyncs/ClientSyncOpinion.cs
Source/Client/ModCompatibilityManager.cs
Source/Client/ModManagement.cs
Source/Client/ModPatches.cs
Source/Client/Multiplayer.cs
Source/Client/MultiplayerMod.cs
Source/Client/PlayerCursors.cs
Source/Client/Sync/SyncDictionary.cs
Source/Client/Sync/SyncHandlers.cs
Source/Client/Windows/HostWindow.cs
Source/Client/Windows/Windows.cs
Source/Common/MultiplayerServer.cs
Source/Multiplayer.csproj

Merge development into master

---

Languages/Czech/Keyed/Multiplayer.xml

New strings translated, some old strings changed.

Updated Czech translation

---

Languages/French/Keyed/Multiplayer.xml

I added every missing "key" and translate every text + make it greater
I tested and look like not breaking the game

French langage update

---

Source/Client/Sync/SyncHandlers.cs

#114 Fixed smokepop pack and broad shield

---

Source/Client/Sync/SyncDictionary.cs

Similarly to #119, it is required by another MP Compat patch I'm working on
Also, I have no idea what's going with `using System;` there.

Added all sublcassess of TransportPodsArrivalAction to SyncDictionary

---

Source/Client/ModManagement.cs

Fix config sync failing when host has a relative -savedatapath

---

Source/Common/ServerConnection.cs

#109 These colours should help most types of colour blindness out.

Colour Blind Changes

---

Source/Client/MultiplayerSession.cs

#97 Fixes the dialog box not showing up when the server is full

---

Source/Client/Patches.cs
Source/Client/Sync/Sync.cs
Source/Client/Sync/SyncHandlers.cs
Source/Common/MultiplayerAPIBridge.cs
Source/Multiplayer.csproj

Those changes depend on this PR for MP API: https://github.com/rwmt/MultiplayerAPI/pull/1

Added methods for syncing Dialog_NodeTree, handling of API changes, fixed and enabled caravan meeting and ransom incidents

---

Source/Client/Windows/Windows.cs

Validate() was using wrong variable when checking for existing save.
I have no idea why it removed and added first line.

Fix existing save check

---

Source/Client/Sync/Game/SyncDelegates.cs

This would cause issues as sync registering of stuff that came after it in the file wouldn't be reached.

Updated names for Gauranlen tree gizmo syncing

---

Languages/Dutch/Keyed/Multiplayer.xml

Update Dutch language

---

Source/Client/Sync/Game/SyncDelegates.cs
Source/Client/Sync/Game/SyncFields.cs
Source/Client/Sync/SyncDictionary.cs

This is NOT related to #213 and does not fix it.

Sync slave interactions and prisoner target ideology

---

Source/Client/Syncing/Dict/SyncDictRimWorld.cs

Original PR: #164. I accidentally made a big mess there trying to update it to most recent master branch, so I made a new branch/PR for it.

Added sync worker for Hediff

---

Source/Common/MultiplayerAPIBridge.cs

Implements API changes from rwmt/MultiplayerAPI#6

Implemented API for checking if we are executing commands

---

Source/Client/Syncing/Game/SyncDelegates.cs
Source/Client/Syncing/Game/SyncMethods.cs

I've tested all but CompSpawnerItems (which seems unused in the game)
The gizmos include:
- CompSpawner and all its variants (Infinite chemfuel spawner, insectoid hives, mechanoid assemblers)
- CompCanBeDormant - mechanoid cluster elements
- CompSendSignalOnCountdown - mechanoid cluster countdown activator
- CompPawnSpawnOnWakeup - mechanoid cluster droppod beacons, capsules
- CompRechargeable - neural supercharger

Synced a couple of dev mode gizmos, closes #200

---

Source/Client/AsyncTime/AsyncTimePatches.cs
Source/Client/Debug/DebugTools.cs

I've accidentally pushed my previous commits to my development branch, so I tried to fix this mess. This caused my previous PR to get auto-closed.
Anyway, I've also fixed dev tools in SP after using them in MP first.

Fix SP letters and dev tools 

---

Source/Client/Syncing/Game/SyncDelegates.cs

All tools from following have been patched:
- GeneUIUtility (ITab_Genes, ITab_GenesPregnancy, Dialog_ViewGenes)
- ITab_Pawn_Gear
- ITab_Pawn_Health

Synced pawn-related ITab dev tools

---

Source/Client/Patches/Abilities.cs

Also, I've turned the postfix into a finalizer for safety in case we set dontSync to true, and we end up with an exception skipping the postfix.

Fixed accuse ability crash

---

Source/Client/Persistent/CaravanFormingPatches.cs
Source/Client/Persistent/CaravanFormingProxy.cs
Source/Client/Persistent/CaravanFormingSession.cs

I have tested it slightly. I've had no issues, but it could use a bit more testing.

Implemented auto selection of travel supplies, closes #332

---

Source/Client/Syncing/Dict/SyncDictDlc.cs
Source/Client/Syncing/Dict/SyncDictRimWorld.cs
Source/Client/Syncing/Game/SyncDelegates.cs
Source/Client/Syncing/Game/SyncFields.cs
Source/Client/Syncing/Game/SyncMethods.cs

- Ejecting from creating xenogerm dialog
- Ejecting from container ITab
- Toggling between allowing all or only specific genes
- Adding/removing genes to the list of genes to (un)load

Synced gene bank interactions

---

Source/Client/Syncing/Game/SyncMethods.cs

An example of how to reproduce the issue with MP/Harmony only (could potentially work with other assignable things like beds):
1. Have at least 2 royal pawns
2. Assign them a throne
3. Accept pawn lending mission
4. Send one of them on that mission in a shuttle
5. Try to unassign them from throne (requires another royal pawn for the gizmo to be enabled)

Fix CompAssignableToPawn.TryUnassignPawn with inaccessible pawns

---

Source/Client/Syncing/Dict/SyncDictDlc.cs
Source/Client/Syncing/Dict/SyncDictRimWorld.cs

This replaces the ones targeting specific classes

Added a general sync worker for LordToil and LordJob

---

Source/Client/Syncing/Game/SyncMethods.cs

This also removes syncing of smokepop belt, firefoam pack, tox pack, and broadshield, as those are now synced indirectly through the new patch introduced here.
On top of that, it also removes the need to sync similar content from mods.

Patch Targeter to sync instantaneous self-cast verbs

---

Source/Client/Debug/DebugActions.cs
Source/Client/MultiplayerData.cs
Source/Client/Syncing/Dict/SyncDictRimWorld.cs
Source/Client/Syncing/ImplSerialization.cs
Source/Client/Syncing/Worker/SyncWorkers.cs

No real use for vanilla-only players. This PR was made primarily for mods needing this.
The method for syncing it is (basically) the same as the one for ThingComp.

Added sync worker for HediffComp

---

Source/Client/Debug/DebugActions.cs

Fix SaveHashes

---

Source/Client/Persistent/ISwitchToMap.cs

Requires rwmt/Multiplayer-Locale#15

Translate "Switch to map" string

---

Source/Client/UI/IngameDebug.cs

This pull request refactors and enhances the `IngameDebug` class in `Source/Client/UI/IngameDebug.cs` to improve the clarity, structure, and functionality of the debug information displayed in-game. 
* Reorganized and categorized the debug information into logical sections, such as core game state, map-specific details, and faction-related data, for better clarity
* Updated panel to dynamically calculate width based on content size, with a cap at 40% of the available screen width for very small resolution sizes
* Added transparency to the debug text when the mouse is not hovering over the debug panel
<p>
</p>
<details closed>
<summary>Full in-game screenshots</summary>
<br>
</details>

Update in-game debug layout, add transparency

---

Source/Client/Patches/Odyssey.cs

- Override call to GetHashCode when updating fish in a water body.
- Created a deterministic version of GetHashCode for the override.

Added fix for fish determinism

---

Source/Client/Syncing/Game/SyncDelegates.cs
Source/Client/Syncing/Game/SyncMethods.cs

Label: 1.6
- Syncing shuttle reset launch cooldown (debug)
- Syncing shuttle fuel fill from cargo on map/world map
- Syncing shuttle launch from world map

Syncs Remaining Shuttle Behavior

---

Source/Client/Patches/GravshipTravelSessionPatches.cs
Source/Client/Persistent/GravshipTravelSession.cs
Source/Client/Syncing/Dict/SyncDictRimWorld.cs
Source/Client/Syncing/Game/SyncDelegates.cs
Source/Client/Syncing/Game/SyncMethods.cs
Source/MultiplayerLoader/MpMethodUtil.cs

Label: 1.6, Odyssey, Enhancement
I refactored the gravship code a bit and plan to do another round on Sunday if I find the time.
Today I found out that I can simply enable compiler generated code in dnSpy and directly read the ordinals of the lambdas.
That makes syncing lambdas so much easier... I’ve been at the point a few times where I thought I finally understood how to count them correctly only to be disappointed. 😅

Refactor gravship implementation

---

.github/workflows/pr-check.yml
Source/Tests/Tests.csproj

Ensures that pull requests compile in both Debug and Release configurations (to account for conditional code) and that all tests pass.

Expand PR workflow checks

---

Source/Client/Patches/Feedback.cs
Source/Client/Syncing/Game/SyncDelegates.cs

Fix feedback for drafted pawn move order

---

Source/Client/Windows/DebugTextWindow.cs

Fix DebugTextWindow clipping

---

Source/Client/Session/Autosaving.cs

Reduces chance of something going wrong and the player losing a save file or some progress on it.

Do not delete the save file until we have a new one written

---

Source/Client/Patches/TickPatch.cs
Source/Client/Session/MultiplayerSession.cs

Minimal code impact fix for inconsistent command handling

---

Source/Client/Syncing/Game/SyncMethods.cs

Sync harbringer tree's prevent cutting gizmo
