Source/Client/Extensions.cs
Assemblies could be in either `ModRoot/Assemblies` or `ModRoot/1.0/Assemblies` directories.
This change allows both to be checked.
=> Assemblies are searched in multiple pre-defined folders

Source/Client/ArbiterPatches.cs, Source/Client/Comp/MapAsyncTime.cs, Source/Client/MainButtons.cs, Source/Client/Multiplayer.cs, Source/Client/Patches.cs, Source/Client/Persistent/Trading.cs, Source/Client/Persistent/TradingUI.cs, Source/Client/Persistent/TransporterLoading.cs, Source/Client/Seeds.cs, Source/Client/SetMapTime.cs, Source/Client/SettingsPatches.cs
Per discussion in Discord, this eliminates the usage of `MpPatch` per @notfood findings that the previous approach in this project for patching multiple targets is no longer supported. There may be another patch required to remove all errors in debug log:
=> Refactors MpPatch patches to use HarmonyPatch

Source/Client/Sync/SyncHandlers.cs
On init of main menu I see
```
Exception during Sync initialization: System.TypeInitializationException: The type initializer for 'Multiplayer.Client.SyncDelegates' threw an exception. ---> System.Exception: Couldn't find method or property <GetGizmos>b__57_2 in type RimWorld.Building_TurretGun
at Multiplayer.Client.Sync.RegisterSyncMethod (System.Type type, System.String methodOrPropertyName, Multiplayer.API.SyncType[] argTypes) [0x0007c] in <4299605cc90a4872a2b4e1a05d81a08d>:0 
at Multiplayer.Client.SyncMethod.Register (System.Type type, System.String methodOrPropertyName, Multiplayer.API.SyncType[] argTypes) [0x00001] in <4299605cc90a4872a2b4e1a05d81a08d>:0 
at Multiplayer.Client.SyncDelegates..cctor () [0x001bb] in <4299605cc90a4872a2b4e1a05d81a08d>:0 
--- End of inner exception stack …
```
=> Fix SyncDelegates TurretGun errors on init

Source/Client/Comp/MultiplayerMapComp.cs
Fixes #33 
Looks like this may have been introduced by a PR merge conflict, as #2 touched the line (but looks correct), yet the merge commit itself has the line doubled f4d8e8261f1733b3a028a6b291a1134ae09f9657
=> Fix infinite dialog creation on Research Completion

Source/Client/Sync/SyncDictionary.cs, Source/Client/Sync/SyncHandlers.cs
This seems to "work", at least, given a save with a Quest available like https://cdn.discordapp.com/attachments/649645755929198604/692684990538055680/desync952PM.zip , hitting Accept no longer causes a desync.
I'm not 100% sure simply writing/reading the quest.id is sufficient, I tried and failed to see a pattern amongst the other SyncDictionary event types.
=> 1.1: Sync Accept Quest

Source/Client/Sync/SyncHandlers.cs
Fixes #32, which said that a desync was detected upon trying to arrest a prisoner, though the actual desync arose from the clients disagreeing on whether there were any prisoner beds.
The relevant code in Building_Bed.cs is:
```
Action confirmedAct = (Action) (() => // IL calls this `<ToggleForPrisonersByInterface>b__0`
{
List<Room> roomList = new List<Room>();
foreach (Building_Bed thing in bedsToAffect)
{
Room room = thing.GetRoom(RegionType.Set_Passable);
thing.ForPrisoners = newForPrisoners && !room.TouchesMapEdge;
for (int slotIndex = 0; slotIndex < this.SleepingSlotsCount; ++slotIndex)
this.GetCurOccupant(slotIndex)?.jobs.EndCurrentJob(JobCondition.InterruptForced, true, true);
if (!roomList.Contains(room) && !room.TouchesMapEdge)
roomList.Add(room);
}
foreach (Room room in …
```
=> Fixed 'toggle prisoner bed' not syncing the correct method

Source/Client/Sync/SyncHandlers.cs
Fixes a shadow-desync: toggling bills (ie. 'Make Simple Meals' in a Cooking Table) from 'Do X Times' to 'Do Until you have X' or 'Do Forever' wasn't synced (though switching back to 'Do X Times' was).
This likely is the cause of Ed Harris's Desync-01 and 07, as if a pawn started work on one client, that wasn't queued up for another client, it would trigger a hard desync "out of the blue".
Prior to the big 'Harmony Pass' 1.1 commit, there used to be 3x calls like this.
=> Fix desync: changing BillRepeatMode to Forever or Until X

Source/Client/Extensions.cs
`traceFrame.GetMethod().MetadataToken` is an assembly-specific hash which differ between builds (such as Linux vs Windows), ensuring that no trace hashes will ever align, and immediate desyncs on load.
I'm now hashing the Method.ToString() (looks like `DMD<DMD<TickManagerUpdate_Patch2>?489914240::TickManagerUpdate_Patch2> (Verse.TickManager )`) with the assembly-specific hashes (`?489914240`) stripped out, which should be functionally equivalent for our purposes.
=> Fixed 'trace hash mismatch' desync on join, between Linux + Windows

Source/Client/Extensions.cs
I had it working with plain `string`'s, and apparently broke it without testing when I moved to StringBuilder, as `AppendLine` uses \r\n on Windows and \n on Linux (because of course it does)
=> Fix Linux-Windows Desyncs - part 2

Source/Client/Sync/SyncDictionary.cs, Source/Client/Sync/SyncHandlers.cs, Source/Client/Sync/SyncSerialization.cs
* Syncs `Verb_CastAbility.OrderForceTarget`, called when a pawn uses a Psychic Ability on something. This required writing a SyncDictionary entry for `Verb_CastAbility` - I wrote one that works for verbs owned by Abilities (which seems to be the case when a pawn Psycasts via the GUI) and Pawns (unsure how to trigger), though there's other possible verb.DirectOwners left unimplemented/unsynced.
* Syncs the 'limit psychic entropy' safety toggle, as otherwise it desyncs when you spam a lot of psycasts in a row with it toggled on only one client. 
Whew, those took a lot of fiddling to figure out >.>
=> Fix #35: sync casting Psychic Abilities 

Source/Client/ClientNetworking.cs, Source/Client/MultiplayerSession.cs, Source/Client/SettingsPatches.cs, Source/Client/TickPatch.cs
Several players in the Discord reported "immediate desync on connect" with no mods on a basic map, in at least 2 cases this was confirmed to be solved by making sure both host and client had the same state for the vanilla setting PauseOnLoad.
There were already patches in place that tried to make the setting return false in multiplayer (`return true` in a Prefix() for a getter = skip the getter = default to false I'm assuming?), but oddly these did not prevent the desync. Viewing a full decompile, I'm baffled as to how the game is circumventing the getter: the patches look valid and are emitting Log.Message("test")'s, just not where it counts?
I'm now both forcing the setter to always set false, and triggering that setter on MultiplayerSession boot, which seems to quell the desync.
=> Force PauseOnLoad to false, misalignment causes desyncs on load

Source/Client/Persistent/PersistentDialogs.cs, Source/Client/Sync/SyncDictionary.cs, Source/Client/Sync/SyncHandlers.cs
* Fix desync "Call Royal Aid" (button next to Draft on any pawn with rank)
* Fix desync "Assign Pawn to Throne" (just like assigning a bed)
* Fix a, probably harmless but red, null reference exception that seems to happen on main menu load
=> Sync 'Call Royal Aid' + 'Assign to Throne'

Source/Client/MultiplayerSession.cs
As the Discord & #12 have been saying, the 2nd load of a multiplayer game causes a crash.
1. load a game (singleplayer or multiplayer)
2. quit to menu
3. load a multiplayer game
4. 💥 
Looking in the `Local\Temp\Ludeon Studios\RimWorld by Ludeon Studios\Crashes\*\Player.log`, I found a stacktrace ending in
```
0x00007FFCBA72E835 (UnityPlayer) UnityMain
0x00007FFCBA9C5D66 (UnityPlayer) PAL_Thread_YieldExecution
0x00000279846E8F0F (Mono JIT Code) (wrapper managed-to-native) UnityEngine.RenderTexture:DiscardContents (UnityEngine.RenderTexture,bool,bool)
0x00000279846E8E6B (Mono JIT Code) UnityEngine.RenderTexture:DiscardContents ()
0x00000279846E8E03 (Mono JIT Code) RimWorld.PortraitsCache:DestroyRenderTexture (UnityEngine.RenderTexture)
0x00000279F4B6438B (Mono JIT Code) …
```
=> Fix crash on 2nd load of Multiplayer game

.gitignore, About/About.xml, Source/Common/Version.cs, workshop_bundler.sh
In lieu of #30, this adds a `workshop_bundler.sh` that copies the appropriate files into a clean directory + zips it.
As I can't actually build 1.0 and don't care enough to figure it out, I've pushed the stable 1.0 assemblies (from the last Workshop release) to a `rw-1.0` branch, so it can be fetched via git at bundle-time.
I initially had this as a `.bat` but Windows doesn't have a zip utility built-in.
=> Add workshop_bundler.sh, for making a 1.0/1.1 compatible zip

Source/Client/ModPatches.cs, Source/Client/Multiplayer.cs, Source/Multiplayer.csproj
This extends the existing "hold shift when looking at Mod list to reveal which are XML mods" behaviour by comparing against the Compatibility Spreadsheet, showing the numbers directly in-game!
I initially had this fetching directly from Google Sheets, but I'll likely run into rate limits that way, so I've extended the Discord bot responsible for replying to mod compatibility checks (which already has a local cache of the spreadsheet, and a /reload command to refresh it) to rehost the sheet in an efficient format. https://github.com/rwmt/DiscordBot-Advisor/pull/1 (though I'll host it until that PR is merged + deployed)
This is compatible with both Fluffy's Mod Manager and the vanilla one.
=> Add Ingame Mod Compatibility Checker

Source/Client/Comp/MapAsyncTime.cs, Source/Client/Comp/MultiplayerWorldComp.cs, Source/Client/MainButtons.cs, Source/Client/Patches.cs, Source/Client/Replays.cs, Source/Client/TickPatch.cs, Source/Client/Windows/HostWindow.cs, Source/Client/Windows/ServerBrowser.cs
Parexy's #10 hooked up the Async Time setting to actually work, but was kinda a messy PR so hasn't been merged yet.
In testing, I found the checkbox misleadingly useless, as loading a replay would always use the replay's state of AsyncTime. I'm now allowing enabling AsyncTime for existing replays, and disabling the checkbox (so its locked on) if the save says it has AsyncTime enabled.
=> Hookup Async Time + allow enabling on existing saves

Languages/English/Keyed/Multiplayer.xml, Source/Client/ClientConnection.cs, Source/Client/ClientNetworking.cs, Source/Client/ModManagement.cs, Source/Client/MultiplayerSession.cs, Source/Client/Windows/DisconnectedWindow.cs, Source/Common/MultiplayerServer.cs, Source/Common/Networking.cs, Source/Common/ServerConnection.cs
Adds a new button to the 'Mod definition mismatch' window that appears when a guest joins a host with differing mods enabled: "Autosync Mod List". It will:
* Subscribe to any Workshop mods the host currently has active, waiting for their downloads/installs to complete
* Set the list of active mods to match the host's, including order. This is functionally equivalent to automating the copying of `ModsConfig.xml`
Caveats:
* it doesn't download non-workshop versions of mods. If they're installed out-of-band, this will still correctly activate them in `ModsConfig.xml`, so that's something!
* it'll display a console error if Workshop cannot be reached, such as for non-Steam installs, and proceed to try setting up ModsConfig. Missing mods are just ignored/not-set.
I expect this to _personally_ …
=> Auto download host's mods on join

Languages/English/Keyed/Multiplayer.xml, Source/Client/ModManagement.cs, Source/Client/ModPatches.cs, Source/Client/Multiplayer.cs, Source/Client/MultiplayerMod.cs
Most users don't know about "hold shift to show mod compatibility", so lets make it on by default, and add a setting to disable it.
Also, what's `[4]` mean? Now there's tooltips explaining!
=> Mod Compatibility: show tooltips, replace "hold shift" with setting (default on)

About/About.xml, Source/Client/Sync/SyncHandlers.cs
Latest update changed signature of `CalculateHiddenSpecialFilters()` to need an argument
Fixes clicking 'Meals' subcategory in the Acceptable Food filter erroring.
=> Fixed filter subcategories erroring as of 1.1.2609

Source/Client/Comp/MultiplayerMapComp.cs, Source/Client/Persistent/TradingUI.cs
The Comms Console opens a `Dialog_Negotiation`, which is a subclass of `Dialog_NodeTree`, but wasn't being caught by the current check - causing an infinite opening loop. Fixes #60
=> Comms Console: fixed window open loop; Fix trading tooltip

Source/Client/Sync/SyncDictionary.cs
`ability.effectComps` must be initialized (which its getter, EffectComps, will do) prior to casting, or the foreach() over `this.ability.effectComps` will throw a null error. If only Rimworld's internals used their own getters...
For reference, the getter looks like
```
public List<CompAbilityEffect> EffectComps
{
get
{
if (this.effectComps == null)
this.effectComps = this.CompsOfType<CompAbilityEffect>().ToList<CompAbilityEffect>();
return this.effectComps;
}
}
```
=> Fix Vertigo Pulse ability desyncing

Source/Client/Sync/SyncDictionary.cs, Source/Client/Sync/SyncHandlers.cs
Most psychic abilities have a single target.
Apparently "Skip" has two (select a pawn to teleport, and a destination), this syncs the second one.
=> Sync 'Skip' psychic ability (has source + dest targets)

Languages/English/Keyed/Multiplayer.xml, Source/Client/ClientConnection.cs, Source/Client/ClientNetworking.cs, Source/Client/ModManagement.cs, Source/Client/MultiplayerMod.cs, Source/Client/MultiplayerSession.cs, Source/Client/Patches.cs, Source/Client/Sync/Sync.cs, Source/Client/Windows/DisconnectedWindow.cs, Source/Client/Windows/Windows.cs, Source/Common/Networking.cs, Source/Common/ServerConnection.cs
This extends #41 's Mod Downloading/Syncing, to include syncing Mod config files too! A dated backup of existing configs is created beforehand, and a 'Restore Last Configs' button is added to the Main Menu if a backup exists that's < 2 weeks old, which will reapply the backup configs (and previously enabled mods), allowing for quickly switching between Multiplayer and Singleplayer mod sets.
Configs are only overridden when the user hits 'Autosync Mods List' in the 'Mod mismatch!' connection error window.
After syncing, a restart is required to apply the new mods/configs - the client'll automatically reconnect to the server after initializing by utilizing `-connect` launch parameter.
Which configs to sync? Good question; for now I've a hardcoded blacklist of what not to sync (client …
=> Auto sync Mods + Mod Configs on Connect

Languages/English/Keyed/Multiplayer.xml, Source/Client/Comp/MultiplayerWorldComp.cs, Source/Client/Windows/Windows.cs, Source/Common/MultiplayerServer.cs
Triggers an Autosave (named) in a more convenient/obvious manner than "Chat -> /autosave -> enter"
Should I also rename "Save replay" to just "Save"? The default are still replays but I'm not sure that's a meaningful word to most players.
=> Add 'Full Save' option to Main Menu -> Save

Languages/English/Keyed/Multiplayer.xml, Source/Client/Windows/HostWindow.cs
> Cody Spring: With Giddy-Up Battlemounts, shooting a ranged weapon from a mount causes everyone to desync when the arbiter is ON.
> But when the arbiter is OFF, I can have three clients on separate machines in front of me and no desyncs occur, all clients show the same projectiles missing, the same hitting causing the same injuries, it's all synced and good. No clients get a desync, so this is suggesting to me that the Arbiter itself may be having an issue, or having a false-positive or something.
>  Cody Spring: we play without arbiter and still get desyncs like normal
> ZoeyVS: I will add, I've managed 100+ hours of Arbiterless gameplay including client Desyncs without it ever breaking the game
> ZoeyVS: And not noticed anything weird either
> ZoeyVS: Also, the performance gain for …
=> Make 'Run Arbiter' a host setting

Source/Client/Comp/MapAsyncTime.cs, Source/Client/Comp/MultiplayerAsyncQuest.cs
Automatically determines which Map's async time to use if a quest targets a map
Uses that AsyncTime to tick for all aspects of that quest
If no map is targeted then use the world time as a fall back
Does not change Quest generation, it is still based on world time
=> Async quest patch

Source/Client/ClientNetworking.cs, Source/Client/Comp/MapAsyncTime.cs, Source/Client/Comp/MultiplayerWorldComp.cs
Ensures World cannot be paused while maps are unpaused, so the world time doesn't fall behind, ensuring questgen/etc will carry on.
Might help #76. Compliments #77 (which moves quests to map-time if they relate to a map, _once generated_)
Should fix quests not generating in Async time, and may solve other related time oddities (from other behaviors being tied to a paused world time).
=> Clamp World's TimeSpeed between min + max map speeds

Languages/English/Keyed/Multiplayer.xml, Source/Client/ModCompatibilityManager.cs, Source/Client/ModManagement.cs, Source/Client/ModPatches.cs, Source/Client/Multiplayer.cs, Source/Client/MultiplayerMod.cs
As suggested/requested by TBob/ZoeyVS:
* Show the Notes from the Mod Compat spreadsheet in the tooltip, as they often contain advice ("everything works as long as you disable X")
* Fallback to a mod name lookup when workshopId not found, such as for non-steam users and local mods.
* ~If a mod is marked "1*", interpret to mean "4 if the MP Compat mod is enabled, otherwise its a 1."~
* Move `UpdateModCompatibilityDb()` from mod init into a lazy loader pattern, so its only fetched once the Mods menu is actually opened. It should load quite quickly (~100ms), and IMO the flicker makes it feel more "live updating" :)
Needs rwmt/AdvisorBot#3 (which is currently live)
=> Mod Compatibility: show notes in tooltip; lookup by name fallback

Source/Client/Comp/MapAsyncTime.cs, Source/Client/Designators.cs, Source/Client/Sync/SyncDictionary.cs, Source/Client/Sync/SyncSerialization.cs, Source/Client/Sync/SyncWorkers.cs
This PR fixes the issue with right clicking gizmos and possibly any use of Designators outside the click/drag framework.
It also fixes a minor bug with the SyncWorker shouldConstruct propagation.
=> Move Designators to SyncSerialization

Source/Client/ClientNetworking.cs
Fix for invalid handling of `-savedatafolder` command line switch when launching arbiter instance (#124)
=> Correct arbiter command line

Source/Client/Sync/SyncDictionary.cs
Additional note: syncing of UnityEngine.Color is required by MP Compat patch I'm working on.
=> Added UnityEngine.Color to SyncDictionary

Source/Client/Multiplayer.cs
Currently, it was calling .GetType() on MethodBase/MethodInfo, which returned type of those classes, instead of the type that the method was from. It wasn't exactly useful when debugging errors.
=> Fix error logging

Source/Client/Patches.cs, Source/Client/Windows/Windows.cs
A few "QoL tweaks" suggested by @ZoeyVS:
- Menu -> Save now defaults to 'Full' (slower save, faster/safer load), may as well for explicit saves
- Rename 'Save replay' to 'Save'
- Move 'Convert to Singleplayer' lower in menu order; it now triggers a MP save first. Apparently converting from Singleplayer back to Multiplayer is unstable, so these moves aims to discourage potentially one-way conversions to SP.
=> Better saving defaults

Source/Client/Sync/SyncHandlers.cs
Forcing a pawn to reload stuff like locust armor was not synced (they could still reload them on their own) - fixed in this PR.
It also fixes it for mods that use it, like Vanilla Weapons Expanded - Grenades.
=> Sync float menu reload option

Source/Client/ModManagement.cs
Fixes #122 by aligning to the consistent `\n` ending (I'm assuming Rimworld is fine with reading \n delimited files on Windows, almost everything is these days)
=> Fix line-ending inconsistencies syncing mod configs on Linux/Windows: always use \n

Source/Client/Sync/SyncDictionary.cs
Added sync worker for RoyalTitlePermitWorker_DropResources, which fixes the error that happened when trying to use it due to the faction not being synced.
The error caused the permit to go on cooldown only for the client that used it, other clients could use it again without any penalties.
=> Fixes drop resources Royal permit error/no cooldown

Source/Client/Sync/SyncHandlers.cs
This fixes farskip. Additionally, one client picking a targetable ability/psycast will no longer cause all clients to start targeting.
This does NOT fix neuroquake ability, and it'll require more work.
One thing we should consider is if we should sync `Ability.QueueCastingJob` for all subclasses of the class Ability. This does not have any effect on the game itself, but it will affect other mods. The only mod I can think of right now it would affect is Corruption - Psykers, and all it would is sync creation of some motes. Any input on this would be appreciated.
=> Changed which methods are synced for abilities/psycasts

Source/Client/DebugActions.cs, Source/Client/Multiplayer.cs
These merely list how Multiplayer sees the types and defs, they're used for connectivity and if they differ connection will be refused.
=> Data dump actions for connection isues

Source/Client/Sync/SyncSerialization.cs
VanillaFramework unveiled some cross OS issue when it comes to loading types. This fix works around the issue in a similar way the Defs are dealt with. The only downside seems to be that protocol version is broken and needs a bump.
=> Fix cross OS types

Source/Client/Desyncs/LogGenerator.cs, Source/Client/Desyncs/SyncCoordinator.cs, Source/Client/Util/Extensions.cs, Source/Client/Util/HarmonyUtil.cs
[The original file from HugsLib](https://github.com/UnlimitedHugs/RimworldHugsLib/blob/master/Source/Logs/LogPublisher.cs)
Looking at the [HugsLib license file](https://github.com/UnlimitedHugs/RimworldHugsLib/blob/master/license.txt), it looks like using code from it should be acceptable, as it has been released into the public domain. A part of the license states:
> Anyone is free to copy, modify, publish, use, compile, sell, or 
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any means.
The log file is included with the desync files, assuming that it has been successfully generated.
The original code has been modified to:
- Remove everything related to publishing the file online
- Removed code, …
=> Added modified version of HugsLib logs to desync files

Source/Client/Native.cs, Source/Client/Util/MpUtil.cs, Source/Common/Version.cs, Source/Multiplayer.csproj
This _seems_ to resolve the only error Harmony 2.2 introduced:
```
System.MissingMethodException: !!0 HarmonyLib.HarmonySharedState.WithState<!0>(System.Func`1<!!0>)
```
Its the only usage of `HarmonySharedState` in the mod, and that class isn't documented in https://harmony.pardeike.net/api/index.html , so I'm guessing its not intended to be part of the public interface, and thus why there was no warning that pardeike was "breaking backwards compatibility" by modifying it (since undocumented interfaces aren't protected by BC).
=> Harmony 2.2 compatibility: remove broken desync trace name tweaks

Source/Client/Syncing/Worker/ReadingSyncWorker.cs, Source/Client/Syncing/Worker/WritingSyncWorker.cs
They already had it as a method, I simply added the override keyword. This needs the appropriate modification in MultiplayerAPI: rwmt/MultiplayerAPI#3
=> Make WritingSyncWorker and ReadingSyncWorker override Bind<T>(ref T obj, SyncType type)

Source/Client/AsyncTime/AsyncTimeComp.cs, Source/Client/Comp/MultiplayerWorldComp.cs, Source/Client/Syncing/Sync.cs, Source/Common/MultiplayerAPIBridge.cs
Requires changes in the API: rwmt/MultiplayerAPI#4
My main motivation behind creating this is that in some of the mods I've patched for MP they open up dialogs or windows - but it does not pause the game in MP like it normally would in SP. This allows to handle this outside of Multiplayer.
I've prepared the PR, but I'm not 100% decided on some details.
First: the name "pause enforcer". I've used it as I could not think of anything better, and would be fully okay with changing it.
Second: location of the list holding all the delegates. Originally I was contemplating between putting them as I did in `AsyncTimeComp`, or inside of `MultiplayerWorldComp`. I'm open to moving it anywhere else if someone were to suggest a better location.
=> Implemented force pause API

Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Game/SyncMethods.cs
This also affects other abilities that require confirmation (due to def having confirmationDialogText filled, as opposed to confirmations from effect comps).
The change here is to call the compiler-generated method which starts casting the ability directly. Right now we're calling the method which checks if confirmation is needed first - so it worked fine in cases where there was no confirmation needed.
The dialog is only opened for the player that clicks the gizmo, and the action is started once the player accepts the dialog.
I've also moved the method registration from the SyncMethods class to SyncDelegates, as the synced methods are now using delegates.
=> Fix neuroquake ability

Source/Client/Patches/Letters.cs, Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Handler/SyncMethod.cs, Source/Common/Networking/Connection.cs, Source/Common/Networking/MpConnectionState.cs, Source/Common/Networking/PacketHandlerAttribute.cs
From my testing, calling FastInvokeHandler.Invoke is around 4-5 times faster than calling MethodInfo.Invoke - which is still far slower than calling the method directly, but ends up being faster than the alternative.
I realize that such a change could be seen as controversial and fully understand it could be rejected. However, I personally believe it could be beneficial if accepted.
=> Replaced MethodInfo with FastInvokeHandler where possible

Source/Client/Syncing/Game/SyncGame.cs
I'm unsure how this exactly happens, but it's happening consistently with Save our Ship 2 torpedoes.
I assumed it'd be better to patch it here instead of doing harmony prefixes to prevent it from being created, as it's (in my eyes) much cleaner solution to this issue. And in case it ever would appear in another mod, it'll help with those situations too.
Fixes one of the issues in rwmt/Multiplayer-Compatibility#167
=> Prevent creation of TabStorageWrapper when storage is a thing/comp with null map

Source/Client/Patches/StylingStation.cs
The pawn was missing ideo, thus ideo button wasn't drawn, and favorite color used color picker rect for position.
=> Fixes display of favorite/ideo color buttons in styling dialog

Source/Client/Patches/StylingStation.cs
Right now in MP, if you order a pawn to use a styling station they'll walk there, only to open the dialog for the player who ordered it, and walk away while that player is modifying their style.
I've modified the behaviour here to not take the job and instead open the dialog for the player who ordered it - the job to change style will be applied after accepting the dialog, like it was previously.
=> Dont start a job to go to the styling station until confirming

Source/Client/Syncing/Game/SyncGame.cs
The syncing for shell selection failed due to ITab_Storage.SelStoreSettingsParent having null map - which is the case with turret/mortar/etc guns, as they're a separate entity.
=> Fixes #303

Source/Client/Syncing/Game/SyncFields.cs
Considering that I was not aware that this interaction even exists, I assume it may be the same for some other people. In that case, here's an image showing which button it refers to:
=> Synced "Execute guilty colonist" action

About/About.xml, Source/Client/Syncing/Game/SyncFields.cs, Source/Multiplayer.csproj
The gizmo toggle was added in (I believe) 1.4.3530, so the reference was update for it.
=> Updated RW ref to 1.4.3530, synced allow hemogen pack gizmo

Source/Client/Patches/Feedback.cs, Source/Client/Syncing/Game/SyncDelegates.cs
The gizmo doesn't need syncing, as the result will get synced through Pawn_JobTracker.TryTakeOrderedJob. On top of that, syncing it basically ignored this fix in a couple of places.
=> Fixed biosculpter cycle confirmation showing for all players

Source/Client/Patches/StylingStation.cs
Seems like pawn rendering now check for the pawn's life stage, and as the tracker was null it was causing exceptions. We also need to set the life stage index, as otherwise the pawns will be drawn as children in the dialog.
=> Fix styling station dialog

Source/Client/Patches/Abilities.cs
This prevents situations where the ability opens a confirmation dialog without actually casting the ability. As mentioned in the comments in the code, this affects sanguophage bloodfeed ability in cases it displays a warning (severe blood loss or death).
=> Stop abilities with confirmation dialogs from being synced

Source/Client/AsyncTime/TimeControlUI.cs
Adding rect.x moved the the line off the screen. Adding rect.y had no effect whatsoever, as it was always 0.
=> Fixed the time controls not showing forced pause/slowdown, fixes #330

Source/Client/Windows/HostWindow.cs
This should make it more clear that it's clickable as right now, unless you hover over the button, there's no indication that it's clickable.
As for how it looks after the change, here's a screenshot:
=> Used CustomButton for autosave unit selection

Source/Client/Comp/MultiplayerWorldComp.cs, Source/Client/Patches/Determinism.cs
There are 2 separate issues fixed here:
- The game was modifying world state outside of ticking (cause pollution retaliation, increase/decrease world pollution)
- Pollution retaliation for sending waste packs back to player was using Unity RNG instead of Verse RNG
=> Fix world pollution desyncs

Source/Client/Syncing/Dict/SyncDictDlc.cs
Unnecessary for MP with no other mods. Added for the purpose of mod compatibility.
All vanilla implementations of IGeneResourceDrain, as well as all modded ones I could find, are a subtype of the Gene class - so for implementation, I check if it's a subtype of it and throw an exception otherwise.
=> Added sync worker for IGeneResourceDrain

Source/Client/Persistent/CaravanFormingSession.cs
As the `meetingSpot` field needs to be re-assigned outside of constructor (passed by ref), it no longer can be readonly.
=> Expose caravan meeting spot and auto select supplies status for caravan forming session

Source/Client/MultiplayerStatic.cs, Source/Client/Syncing/Game/SyncMethods.cs
This should fix the (surprisingly) rare situations when a class we're patching includes a method with same name but different parameters.
Currently, this fixes a conflict with Vehicle Framework.
=> Fix ambiguous match on `GetMethod` calls when looping over `AllSubtypesAndSelf`

Source/Client/Saving/CrossRefs.cs
Currently, sending a transport ships in some circumstances (like summoning one through royal permits) would result in them disappearing with all pawns and items they carry when arriving at their destinations.
The issue was caused due to transport ships themselves not being registered in shared cross refs, which caused them to fail syncing them as IExposable.
=> Fix (Royalty) transport ships

Source/Client/Saving/CrossRefs.cs
`MapDeiniter.Deinit` is marked as obsolete, never called from vanilla code, and calls `MapDeiniter.Deinit_NewTemp`. Unless there is a reason for it, I don't see why the patch should apply to the obsolete method anymore.
=> Change the patch on `MapDeiniter` to target `Deinit_NewTemp` instead of `Deinit`

Source/Client/Syncing/Game/SyncDelegates.cs
`ShipJob_Wait` is synced slightly below, on lines 104-105 (or 105-106 before this change):
https://github.com/SokyranTheDragon/Multiplayer/blob/a3a8c5e530798cccc887fcaaaba1de74cbc8e1aa/Source/Client/Syncing/Game/SyncDelegates.cs#L104-L105
=> Remove duplicate sync method lambda.

Source/Client/Syncing/Dict/SyncDictRimWorld.cs
This came up as minor inconvenience when patching Vehicle Framework, so I've decided to make sure those can handle null values. Could come in handy in the future.
=> Change Lord, LordJob, LordToil sync workers to handle null

Source/Client/Syncing/Game/SyncDelegates.cs
The first one doesn't use the map, but syncing uses `Find.CurrentMap` in `TransformField`. The second one call `Designator.Map`, which in turn calls `Find.CurrentMap`.
=> Fix designator right click float menus with multiple maps

Source/Client/Patches/Patches.cs
This fixes issue of copy/paste gizmos not working properly for:
- Growth vats (`Building_GrowthVat`)
- Biosculpter pods (`CompBiosculpterPod`)
- Mortars (`CompChangeableProjectile`)
The issue happened due to the storages associated to those losing their owner after loading them through `ExposeData`. The solution was to re-assign their owner in PostLoadInit.
The patch is included in the generic `Patches.cs` file, as I felt it did not really fit any other existing source file containing patches (potentially could fit into `VanillaTweaks.cs`).
However, if needed I could create a separate file for them or move them to a different location. I can also split them into separate patches, so a single class doesn't contain 3 postfixes (I've put them all in the same class to have basically-identical …
=> Fix syncing of copy/paste gizmos for Biosculpter/Growth Vat/Mortar, fixes #255

Source/Client/Patches/TeachingPatches.cs
This should prevent the teacher being set in interface for the student. However, the teacher will be set for the student after syncing.
=> Fix prioritize teaching interaction, fixes #359

Source/Client/Patches/TimestampFixer.cs, Source/Client/UI/Layouter.cs, Source/Client/Util/TypeCache.cs
Occurrences of `ContainsKey` followed by indexer getter/setter were replaced by `TryGetValue`/`TryAdd`. In both cases they'll have the same effect.
This also fixes a minor issue with `TypeCache` where `typeByFullName` would check for existence of `Type.Name`, but insert `Type.FullName`.
For extra context/explanation behind dictionary operation changes:
`TryAdd`, `Add`, and indexer all use the same method for adding to dictionary (`TryInsert`, using a different `InsertionBehavior`). This also means that all of them do a check if a value exists in the dictionary before adding the value - and this is the only way they differ. When an entry with a given key exists `TryAdd` just returns early, `Add` will throw an exception, and indexer setter will replace it.
As for `TryGetValue` - it just …
=> Optimize operations on dictionaries, fix small issue

Source/Client/Desyncs/SaveableDesyncInfo.cs
As far as I'm aware, this information is currently not included in the desync logs. It was sometimes possible to determine if it was by analyzing log files or desync files, but it was not an ideal solution.
Having this info could occasionally prove useful, especially if person sharing the logs is currently not able to respond when asked if async/multifaction were active.
=> Include if async time and multifaction are active in desync logs

Source/Client/Session/PlayerInfo.cs, Source/Client/UI/CursorPatches.cs
Due to absence of any discussion around the issue and the approach for the solution, I've decided to just make a PR with one possible solution that I deemed the most straightforward.
The solution uses Vanilla `SelectionDrawer.DrawSelectionBracketFor` while providing the specific material, which will handle the color. The method was likely changed in 1.4 to support custom materials due to the need of custom colors for the selector due to storage groups.
The materials are stored inside of `PlayerInfo` object. The materials are created using `MaterialPool.MatFrom`, so they should be cached by the game (and will be re-used if a player leaves and rejoins).
`MaterialPropertyBlock` could no longer be used here due to the Vanilla method not using it, as it instead opted into using `Material` to …
=> Fix #410, update MP selector drawing

Source/Client/Patches/MultiplayerPawnComp.cs
If a pawn has no comps, then `ThingWithComps.comps` is never initialized and being left as null, in which case `ThingWithComps.AllComps` will return `ThingWithComps.EmptyCompsList`.
The fix here is to initialize `ThingWithComps.comps` if it was null.
=> Fix MultiplayerPawnComp init for pawns with no comps (like Toxalope)

Source/Client/Multiplayer.csproj, Source/Common/Common.csproj, Source/MultiplayerLoader/MultiplayerLoader.csproj
Considering that in About.xml we mention that MP requires v1.4.3901, we may as well use NuGet package for that specific version.
This doesn't really change anything besides that, but should ensure we don't touch anything that may have been removed and that we'll be able to reference anything new in code.
The NuGet reference was a bit inconsistent across projects, since Multiplayer and the Loader were both using 1.4.3704, while Common was using 1.4.3551-beta.
=> Update Krafs.Rimworld.Ref NuGet package to 1.4.3901

About/About.xml
This is a minor change that shouldn't really affect anything. The main purpose of this is to try and enforce more proper load order, similarly to the reason we list HugsLib as a mod that we should load before. It may not be a perfect solution, but it'll definitely help for players unaware of the position MP should take, or those who only use built-in sorting functionality.
HugsLib is no longer receiving support and contains some bugs, and some mods are dropping it as dependency due to this. Meanwhile Vanilla Expanded Framework is seeing more and more use - be it from new Vanilla Expanded mods, or even unrelated mods that are using it for its features. It'll very likely keep getting supported, so it should stay relevant for long.
=> Added rule to load before Vanilla Expanded Framework

Source/Client/AsyncTime/TimeControlUI.cs
Very small QOL improvement to flash a red pulse (like the threat letters) under the blocking pause indicator.
Given a non-async time game is running
When a player opens a dialog that pauses the game
Then a red pulse will be animated periodically near the colonist bar's blocking pause indicator for all players.
Multiple simultaneous blocking pauses from different maps will flash independently.
I chose 6 seconds as the pulse interval.
=> Animate red flash for blocking pause dialogs

Source/Client/Syncing/Handler/SyncDelegate.cs
Currently, exposing fields expects the method to provide a full path to the fields, instead of a field relative to the parent object.
For example, before this change the paths needed to be: `RimWorld.SocialCardUtility+<>c__DisplayClass42_1/roleChangeRitual`, `RimWorld.SocialCardUtility+<>c__DisplayClass42_1/ritualTarget`, `RimWorld.SocialCardUtility+<>c__DisplayClass42_1/CS$<>8__locals1/pawn`
After this change, the paths now need to be:
`roleChangeRitual`, `ritualTarget`, `CS$<>8__locals1/pawn`
On top of that, exposing the fields had no effect on reading them, which caused reading to fail due to the types not having sync workers. This will fix it by actually exposing the fields while reading.
=> Fix exposing fields for SyncDelegates

Source/Client/Syncing/Dict/SyncDictDlc.cs, Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Game/SyncMethods.cs
- Updated lambda ordinals for `FloatMenuMakerMap` and `MechanitorUtility` delegates
- Changed syncing of carry to shuttle lambda delegate to a local func
- Removed syncing of `RoyalTitlePermitWorker_CallLaborers.CallLaborers`, as it's no longer needed since it'll be synced from `ITargetingSource.OrderForceTarget`
- Added a sync worker for `RoyalTitlePermitWorker_CallLaborers`, as using that permit would otherwise desync
- Added syncing of non-virtual `Verb.TryStartCastOn` method
- It's required for ability syncing, as it can be called from `Ability.QueueCastingJob` (the `LocalTargetInfo` variant) if `verbProps.nonInterruptingSelfCast` is true
- Modified `Targeter.BeginTargeting` patch to not handle `Verb.TryStartCastOn` calls
- This is due to the previous change handling syncing of this …
=> Update current sync methods and delegates

Source/Client/ExternalAnnotations/0Harmony/Annotations.xml, Source/Client/ExternalAnnotations/Assembly-CSharp/Annotations.xml
- Updated all the RimWorld's debug attributes to use `LudeonTK` namespace
- Added `DebugActionYielderAttribute` to the implicit use attributes
- Changed all external annotation xml files to use 2 spaces, matching `.editorconfig` style
=> Update external annotations

Source/Client/Networking/JoinData.cs, Source/Client/UI/IngameDebug.cs, Source/Client/UI/MainMenuAnimation.cs
Minor change that should not really affect anything, as `Enumerable.Count()` would still end up calling `list.Count`:
```csharp
switch (source)
{
// Skipped irrelevant code
case ICollection<TSource> sources:
return sources.Count;
// Skipped irrelevant code
}
```
=> Replace Enumerable.Count(list) with list.Count

Source/Client/Multiplayer.csproj, Source/Client/Persistent/PersistentDialogs.cs, Source/Common/Common.csproj, Source/MultiplayerLoader/MultiplayerLoader.csproj, Source/Server/Server.csproj, Source/Tests/Tests.csproj, Source/TestsOnMono/TestsOnMono.csproj
Dependencies update to the latest version (in solutions using those):
- `Lib.Harmony` from 2.2.2 to 2.3.3
- `Krafs.Rimworld.Ref`
- Updated from 1.5.4055-beta to 1.5.4062 in `Multiplayer.csproj`
- Updated from 1.4.3901 to 1.5.4062 in `Common.csproj` and `MultiplayerLoader.csproj`
- `Krafs.Publicizer` from 2.0.1 to 2.2.1
- This includes changes done automatically when updating, namely adding `PrivateAssets` and `IncludeAssets` in .csproj files
- `Zetrith.Prepatcher` from 1.1.1 to 1.2.0
An additional (and required) change is that `PresistentDialogs` now uses an explicit call to `Extensions.GetDefaultValue`. This is done due to a name conflict with `AccessToolsExtensions:GetDefaultValue`. (Perhaps we should use Harmony's `GetDefaultValue`, as it also handles `null` and `typeof(void)` types?)
=> Update RimWorld related dependencies

Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Game/SyncMethods.cs, Source/Client/Syncing/Handler/SyncMethod.cs
None of the psychic ritual gizmos were synced yet.
Some of those sync lambda methods/delegates likely could have been synced through a different, non-lambda method. As I was going through the list of gizmos in the game I didn't really consider it for some of them at the time.
For obvious reasons, the Anomaly exclusive gizmos could not be tested until the DLC releases.
All non-dev mode non-Anomaly gizmos were tested. A big portion of dev mode gizmos was tested as well.
Additional info:
- The 3 new sync workers are needed for some of the dev mode gizmos
- `TradeRequestComp` sync worker is not needed, as it's a subtype of `WorldObjectComp` and we have an implicit sync worker for it
- A dev mode gizmo for `CompToxifier` needed to be synced as it would cause infinite loop otherwise (it would …
=> Sync majority of new gizmos added in 1.5/Anomaly

Source/Client/AsyncTime/TickRatePatch.cs
Using the switch should allow compiler to better optimize the method (looking at decompiled code and IL code, it seems it is the case for this method).
We could use the switch expression instead of the switch statement - the issue with that however is that it introduces a temporary variable in compiled code (the value it later assigns to __result), as well as it needs the values to be floats explicitly as it'll otherwise use an int variable that it later converts to float.
Adding the Ultrafast speed doesn't really change much - the biggest change I've seen is that some mods that display target tickrate will now do so correctly on speed 4, where they previously would show incorrect value of 60.
=> Added Ultrafast speed to TickRatePatch, changed if/else to switch

Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/Syncing/Game/SyncFields.cs, Source/Client/Syncing/Game/SyncMethods.cs
Changes:
- Added a sync worker for `Pawn_GuestTracker`, as it's needed for the sync methods
- Synced non-exclusive prisoner interaction modes
- This affects hemogen farm and bloodfeed (as well as extra modes added by mods)
- The synced method is `Pawn_GuestTracker:ToggleNonExclusiveInteraction`
- As opposed to normal prisoner/slave interaction modes, it would not be possible to sync it as a field since the field is a list of allowed modes
- Changed syncing of exclusive prisoner interaction modes by using a sync methods rather than sync fields
- The synced method is `Pawn_GuestTracker:SetExclusiveInteraction`
- The changes to the field didn't need to be handled as a sync field anymore, so I've changed it to a sync method
=> Sync non-exclusive prisoner interaction mode, change syncing exclusive mode

Source/Client/MultiplayerStatic.cs
It was excluded due to it calling `MakeBombardmentMote_NewTmp`, which would cause warnings from Harmony. However, at some point the `_NewTmp` method was removed (it's not there in the latest 1.4 release). The exception to the patches can now be removed without HugsLib complaining.
=> Stop excluding "MakeBombardmentMote" from mote patches

Source/Client/Syncing/Dict/SyncDictRimWorld.cs
It seems a second StorageGroup sync worker was added recently, but the old one was kept in. I've removed the old one since the new one seems to be better (as it doesn't rely on a `Thing`, just a map and ID).
On top of that, I've merged the two regions named Storage.
=> Remove a duplicate StorageGroup sync worker, merge both storage regions

Source/Client/Persistent/CaravanSplittingProxy.cs
- The cancel button will be red to match the behaviour of other session dialogs
- The proper translation key is used for travel supplies tab
- GUI.Begin/EndGroup was replaced by Widgets.Begin/EndGroup to match vanilla dialog (it seems Widgets call fixes some Unity bugs on Linux/Steam Deck)
- Removed a lot of temporary variables in DoBottomButtons
- Cleaned up CaravanUIUtility.DrawCaravanInfo call by removing default values, removing `new int?()`, and inverting the conditional operator
=> Minor maintenance on CaravanSplittingProxy

Source/Client/Patches/Patches.cs
Remove the storage parent fix (#407) for growth vat, as this was fixed by vanilla.
=> Remove growth vat storage owner patch (fixed in vanilla)

Source/Client/Patches/Determinism.cs
`GameConditionManager.MapBrightnessTracker:Tick` uses `Time.deltaTime`, the value of which will be different between the players. With similar FPS they'll be very close to one another, but if there's a big change between FPS values (for example, 60 and 144) the issue will be much bigger.
The issue with `MapBrightnessTracker` is the map will get darker at a different rate for each player - in one of my tests, the client finished the transition 10 ticks faster than the host.
The fix here is rather simple - replace `deltaTime` with a constant value of `1 / 60` or `0.166666...` to ensure each 60 ticks in-game will be treated as a second, no matter the game speed.
=> Fix GameConditionManager.MapBrightnessTracker (Unnatural Darkness) desyncs

Source/Client/Persistent/MapPortalPatches.cs, Source/Client/Persistent/MapPortalProxy.cs, Source/Client/Persistent/MapPortalSession.cs
Requires rwmt/Multiplayer-Locale#20 for the text
=> Added session for map portals

Source/Client/Syncing/Dict/SyncDictDlc.cs, Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Game/SyncFields.cs, Source/Client/Syncing/Game/SyncMethods.cs
I'm trying to avoid (too many) spoilers about anomaly, so I'm patching stuff as I go through and progress the DLC. I've gone through and tested some of the stuff that I already saw in game, and fixed whatever needed fixing.
Changes:
- Creating corpse stockpile for harbinger trees needed `SyncContext.MapSelected`
- Synced a float menu option for capturing entity into any holding building
- The interaction would work if selecting a specific holding building
- Synced a float menu option for drafted carrying an entity to a holding building
- It was not needed, but was synced like the other similar methods to save up on the amount of data that would end up being synced
- Moved the gizmo for carry to shuttle interaction lower, as the other sync delegates were ordered by their `lambdaOrdinal`
- …
=> More Anomaly syncing

Source/Client/Debug/DebugActions.cs, Source/Client/Syncing/Game/SyncMethods.cs
Synced all implementations of `IRenameable.RenamableLabel` setter for types that can be synced.
I've decided to only apply the sync worker for types that can be synced for safety, as the rename dialogs are of low enough importance that encountering errors or other issues because of them would not be desirable. After all, if rename dialog is not synced then it should not cause any issues besides a minor visual desync (unless there's a mod that does something special with the name, which I've not really encountered).
I've wrapped the portion of the code registering it in a double call to `LongEventHandler.ExecuteWhenFinished` to ensure it runs after MP Compat's late patches, ensuring all Sync Workers will be registered by it at this point.
Because of no logging when there's `IRenameable` …
=> Sync rename dialogs (sync IRenameable.RenamableLabel setter)

Source/Client/Patches/Determinism.cs
Info on `UndercaveMapComponent:MapComponentTick` and why it needs patching:
- RNG calls after current map/visible camera area checks
- Majority of the RNG calls are visual/audio effects only
- `TriggerCollapseFX` does have an effect on simulation by spawning collapsed mountain roof
- The collapsing rocks have minimal impact on the game, as they avoid player pawns
Fixing RNG is easy by just pushing/popping the state.
Fixing the collapsed mountain roof is more complex. Possible solutions:
- Disable rock collapse completely
- Disable current map checks (suboptimal for performance)
- Disable the existing calls to `TriggerCollapseFX` and call it in a deterministic way (used in this PR)
Information about the patch:
- The transpiler will make the call to `Rand.MTBEventOccurs` always fail, making …
=> Patch for UndercaveMapComponent (pit gate)

Source/Client/Patches/Determinism.cs
Zetrith provided the fix on Discord and pointed out that it seems to be inlining issue. It was the first time I've dealt with an issue like this, so I greatly appreciate it. I've spent several day investigating the issue and have just reached a dead end.
This should fix the issue with Vanilla Expanded Framework. Using this fix I was not able to reproduce the issue anymore.
=> Add EarlyPatch attribute to PawnTweener.TweenedPos patch

Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Game/SyncMethods.cs
RW update add `_NewTemp` methods instead of replacing existing ones to keep backwards compatibility with mods. This allows mods calling those methods to work as they used to, but it causes issues with Harmony patches since those are no longer called by vanilla code. The change here is to target the `_NewTemp` methods Harmony patches (sync methods) rather than the original ones.
This should fix changing heater/cooler temperature settings as well as giving the players time to rename stillborn pawns (normally would be 1 tick in this situation).
=> Fix issues due to _NewTemp methods, fixes heater/cooler temperature changes

Source/Client/Patches/Determinism.cs, Source/Client/Patches/Patches.cs
This should fix the issue with Noctol eyes, along with other attached motes being drawn away from the pawns they are attached to. This was likely never really noticed before due to no other vanilla attached motes having their position as important as here.
Getting a DrawPos of a pawn during ticking will cause `PawnTweener.TweenedPos` to return `TweenedPosRoot` in MP to make the method deterministic. However, `MoteAttached` updated during simulation will draw it in an incorrect position due to the pawn position not being where it is visually.
The fix here is to cause `PawnTweener.TweenedPos` patch not to run while calculating the position of the attached mote.
Potential alternative approach would be to make a method that works like `Pawn_DrawTracker.DrawPos`, but using …
=> Update position of attached motes based on real position 

Source/Client/Patches/Seeds.cs
Previously, we've used a constant seed for long events. This change will replace it with a randomized seed which is selected whenever a long event is queued.
This should allow for more randomness in long events, and is required by the labyrinth map generation to produce unique maps, instead of only having a single possible layout.
=> Use a randomized seed for long events

Source/Client/Syncing/Game/SyncDelegates.cs
It was synced by `PersistentDialog` syncing if the dialog was opened by interacting with the joiner pawn. However, it is not synced when interacted using the choice letter (which this PR fixes).
Preferably, we'd disable the dialog opening when interacted (and only allow through choice letter) since it opens it for all players, and is rather disruptive. However, I'm leaving it for another PR.
=> Synced ChoiceLetter_AcceptCreepJoiner

Source/Client/MultiplayerStatic.cs
The method calls random whenever the mote is null or destroyed. There may be situations where the mote ends up being created late or destroyed for some players, but not the others. This is guaranteed to happen when playing with multiple maps, and seems like it may happen when the game is not paused when someone is joining.
Since the desync happens due to RNG call to randomize the mote position, this change should fix it by pushing/popping the RNG state before/after the method is called.
=> Fix desyncs due to CompCableConnection motes, fixes #447

Source/Client/Patches/Determinism.cs, Source/Client/Patches/Patches.cs
This should fix #447, rendering #481 unnecessary. I've decided to still leave that code as an extra safety precaution, but it should be now safe to revert those changes.
As for the changes/fixes, this should fix issues with Bioferrite Harvester and Electroharvester cables not creating motes after switching maps. Additional minor change is that FixNullMotes patch was moved from generic "Patches" to "Determinism", as the patch itself changes some non-deterministic behavior.
The current `FixNullMotes` patch would create a single mote per mote's `ThingDef.thingClass` and then reuse it. It ensured that the call to `MoteMaker.MakeStaticMote` never produced null, however the mote itself was more of a dummy mote (not initialized with any data).
This caused issue with the cables that would …
=> Rework FixNullMotes patch

Source/Client/Syncing/Game/SyncDelegates.cs
In 1.4 this was a delegate we needed to sync, but now it's just a normal method. Trying to sync `LordToil_BestowingCeremony_Wait` as a delegate failed, causing errors.
=> Fix starting bestowing ceremony using right-click

Source/Client/Factions/FactionRepeater.cs
This should fix the issues with extra missions generating (and often causing errors) due to the game trying to generate them for the Spectator faction.
=> Exclude Spectator faction from FactionRepeater

Source/Client/AsyncTime/SetMapTime.cs
In simple terms, this will fix issues with condition causers, like smoke spewer or psychic suppressor sites.
`CompCauseGameCondition` iterates over the list of each maps that it affects, where it either creates the game condition, or updates the remaining ticks for it.
The issue is that it uses `Find.TickManager.TicksGame` when doing so, which causes the affected maps to receive the time from either the world (if the `Thing` the comp is part of happens to be attached to a world object), or the specific map (if the `Thing` is spawned on an actual map).
The change here is to properly use the actual ticks from the specific map that is affected.
A slight side note - this won't fix maps where the game condition is active, but the condition causer was destroyed. This is due to the condition …
=> Make AOE game condition causer use correct map time, fixes #210

Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Game/SyncMethods.cs
`Comp_AtmosphericHeater` is a subtype of `CompTempControl`, but has the `CompGetGizmosExtra` method rewritten. The +/- 1/10 degrees change was working fine, as it called the synced method `InterfaceChangeTargetTemperature_NewTemp`. However, this was not the case for the reset gizmo, as it set the temperature directly. I've synced the reset gizmo for the atmospheric heater itself, so it should work fine now.
Also moved the `CompTempControl` gizmo syncing from `SyncDelegates` to `SyncMethods`, right next to where the other sync method for the type was registered. I believe it should have been there to begin with, and I must have made a mistake while working through all the new and changed gizmos in 1.5.
=> Sync atmospheric heater "reset" gizmo

Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/Syncing/Game/SyncMethods.cs
This should sync stop research, dev finish now, and dev apply techprints. This required a sync worker delegate for `ResearchManager` to work.
I've decided to include `ResearchManager` sync worker in the `Game` region, as it's a game-wide element (doesn't matter where in the world your colony is, the research will be accessible by you). I've done so since `AreaManager` and `AutoSlaughterManager` are included under the `Maps` region. However, @Zetrith if you'd prefer me to change it and either move it to an existing region or make a new region (`Research`?) - just let me know and I'll update the PR.
I've left the current syncing for selecting research by using `MainTabWindow_Research.DoBeginResearch`, and made `ResearchManager.SetCurrentProject` debug-only. I've done this due to …
=> Synced all research tab buttons, fixes #290

Source/Client/Syncing/Game/SyncMethods.cs
I think I must have used the API out of habit when writing this code, my bad. I've changed the code to use `SyncMethod.RegisterSyncMethod` and `SyncMethod.Register` rather than `MP.RegisterSyncMethod`.
This shouldn't change any functionality and is here mostly for consistency.
=> Register sync methods directly rather than using API

Source/Client/AsyncTime/AsyncTimeComp.cs, Source/Client/Patches/PawnTable.cs, Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/Syncing/Game/SyncMethods.cs
This change is primarily to fix `PawnColumnWorker_Designator` and `PawnColumnWorker_Sterilize` displaying confirmation dialogs, which caused issues as pressing the checkbox would open the dialog for all players and the dialogs themselves weren't synced. I've mentioned this issue in #429.
The first change is to stop syncing `PawnColumnWorker_Designator.SetValue` and `PawnColumnWorker_Sterilize.SetValue`, as those could display confirmation dialogs. Instead of those 2 methods, we instead sync:
- `DesignationManager.AddDesignation`
- This one is not needed, but was included for consistency with adding `DesignationManager.RemoveDesignation` (and may come in handy for mod compat, it can be safely removed if desired)
- `DesignationManager.RemoveDesignation`
- Called from …
=> Rework some PawnColumnWorker syncing

Source/Client/Syncing/Dict/SyncDictRimWorld.cs
When a pocket map is generated, it is added to `Find.World.pocketMaps` rather than `Find.World.worldObjects.AllWorldObjects`.
This change will make sync worker fallback to pocket maps list if it did not find the map in world objects list.
=> Update WorldObject sync worker delegate to handle pocket maps

Source/Client/AsyncTime/AsyncTimeComp.cs, Source/Client/AsyncTime/AsyncTimePatches.cs, Source/Client/AsyncTime/SetMapTime.cs, Source/Client/Factions/FactionCreator.cs, Source/Client/Factions/FactionSidebar.cs, Source/Client/Factions/Page_ChooseIdeo_Multifaction.cs, Source/Client/Factions/Page_ConfigureStartingPawns_Multifaction.cs, Source/Client/Networking/HostUtil.cs, Source/Client/Patches/MapSetup.cs, Source/Client/Saving/SavingPatches.cs, Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/Util/MpUI.cs
#
Please read this:  https://github.com/rwmt/Multiplayer/pull/508#issuecomment-3001301442 ♥
#
Hello :)
I'm new to modding but have a degree in computer science, along with general experience in game development, especially in Unity and its Netcode networking library. I'm very open to feedback and happy to make any code adjustments as needed.
I've spent considerable time playing RimWorld with this mod and the multifaction feature enabled, which has inspired me to improve the starting experience specifically for multifaction gameplay.
**General Updates:**
- Enhanced multifaction starting experience for Core, Biotech, and Ideology to mirror single-player starts.
- Scenario selection is now available before creating a new faction.
- Correct starting gear, possessions, research, and initial …
=> Improved starting experience for multifaction

Source/Client/Networking/State/ClientJoiningState.cs, Source/Client/Networking/State/ClientLoadingState.cs, Source/Client/Networking/State/ClientPlayingState.cs, Source/Common/Networking/MpConnectionState.cs, Source/Common/Networking/PacketHandlerAttribute.cs, Source/Common/Networking/State/ServerPlayingState.cs
`IsFragmented` doesn't mean anything on its own, i.e. it's almost certainly a mistake to use it without an accompanying `PacketHandler` attribute. It makes more sense to just add it as a field to `PacketHandler`.
=> Integrate IsFragmented into PacketHandler

Source/Client/Syncing/Dict/SyncDictRimWorld.cs
Introduces a SyncWorker delegate for handling ThingDefCount synchronization.
This is needed for #508 to sync pawns starting possessions and ensure they are generated correctly on the map after pawn creation.
Per Sokyran's suggestion, this functionality is split into its own PR, as it could be useful for other cases as well.
=> Add SyncWorker for ThingDefCount serialization

Source/Client/Networking/JoinData.cs, Source/Client/Networking/NetworkingLiteNet.cs, Source/Client/Networking/NetworkingSteam.cs, Source/Client/Networking/State/ClientJoiningState.cs, Source/Client/Networking/State/ClientPlayingState.cs, Source/Client/Session/MultiplayerSession.cs, Source/Client/Session/PlayerInfo.cs, Source/Client/Util/Extensions.cs, Source/Common/ByteReader.cs, Source/Common/ByteWriter.cs, Source/Common/Networking/ConnectionBase.cs, Source/Common/Networking/State/ServerJoiningState.cs, Source/Common/Networking/State/ServerPlayingState.cs, Source/Common/PlayerManager.cs, Source/Common/ScheduledCommand.cs, Source/Common/ServerInitData.cs, Source/Common/ServerPlayer.cs, Source/Common/Syncing/Logger/LoggingByteReader.cs, Source/Common/Syncing/Logger/LoggingByteWriter.cs, Source/Common/Util/EnumCache.cs, Source/Common/Version.cs
This makes the code clearer, it's more convenient than casting to number-types, and is smaller on the wire (as some enums were needlessly sent as an int).
=> Introduce Byte{Reader,Writer}.{Read,Write}Enum

Source/Client/Multiplayer.csproj, Source/Common/Common.csproj, Source/MultiplayerLoader/MultiplayerLoader.csproj, Source/Server/Server.csproj, Source/Tests/Tests.csproj, Source/TestsOnMono/TestsOnMono.csproj
This pull request upgrades .NET versions across all projects and updates  the `Lib.Harmony` package to a newer version.
* Updated target framework from `net472` to `net48` in `Multiplayer.csproj`, `Common.csproj`, and `MultiplayerLoader.csproj` for compatibility with newer .NET features
* Updated target framework from `net6.0` to `net8.0` in `Server.csproj` 
* Upgraded `Lib.Harmony` package from version `2.3.3` to `2.3.6` across all projects
=> .NET Framework 4.8 & .NET 8 upgrades

Source/Client/Patches/HashCodes.cs, Source/Client/Util/DeterministicHash.cs
- Added Deterministic HashCombineInt for 3,5,6,7 and 8 combinations. (2 and 4 are already included in RimWorld)
- Patched all version of System.HashCode.Combine which will cover all future functions of this to.
=> Deterministic HashCombines

Source/Client/AsyncTime/TimeControlUI.cs, Source/Client/Factions/Dialog_ChooseFactionColor.cs, Source/Client/Factions/FactionCreator.cs, Source/Client/Factions/FactionExtensions.cs, Source/Client/Factions/FactionSidebar.cs, Source/Client/Factions/MultifactionPatches.cs, Source/Client/Factions/Page_SelectScenario_Multifaction.cs, Source/Client/Factions/SidebarPatch.cs, Source/Client/MultiplayerGame.cs, Source/Client/Settings/MpSettings.cs, Source/Client/Settings/MpSettingsUI.cs
+ UI redesigned without using `Layouter.cs`.
+ Faction color added.
+ Better scenario chooser added.
+ `Select Random Site` button added.
+ `World Factions` button added.
+ `Locate on map` button added for Join Faction list.
https://github.com/user-attachments/assets/c9fa9cad-290a-4763-a2dc-7e355a982312
+ `Colonist Bar` removed.
+ `World Route Planner` removed.
+ `Send Caravan` removed.
+ `Quests` removed.
+ All `MainButtonDef` except for the `Menu` and `World` ones removed.
+ Toggle button for quest filter added.
https://github.com/user-attachments/assets/d9748ae0-f951-4168-8d26-70f15780eaa3
+ Added option to hide other players in colonist bar.
https://github.com/user-attachments/assets/9cd7098c-2a17-409f-8d81-f3158dc1f990
+ `hideOtherPlayersInColonistBar`, `hideOtherPlayersQuests` added …
=> Improved Faction Sidebar and more

Source/Client/AsyncTime/AsyncTimeComp.cs, Source/Client/AsyncTime/AsyncWorldTimeComp.cs, Source/Client/Patches/VTRSyncPatch.cs, Source/Common/CommandType.cs, Source/Common/Networking/State/ServerPlayingState.cs, Source/Common/PlayerManager.cs, Source/Common/ServerPlayer.cs
Variable tick rate implementation
- Standard VTR of 1 on any map that has any players
- Any other maps run at 15 (ticks every 15 ticks instead of every 1)
- Keeps track of player count on each map now via a new command
Updates:
- Now correctly update map player counts on unexpected disconnects
- Handled Projectile and WorldItem VTR
- No longer counts a player as on a map if they have the world map open (Need to test Odyssey scenarios)
NOTE: This will not work by itself, it needs other general 1.6 updates as found in my other PR
I separated this one as I think it could have some discussion around the best way to implement it.
=> Variable Tick Rate

Source/Client/OnMainThread.cs, Source/Client/UI/DebugPanel/DebugLine.cs, Source/Client/UI/DebugPanel/DebugSection.cs, Source/Client/UI/DebugPanel/PerformanceCalculator.cs, Source/Client/UI/DebugPanel/PerformanceRecorder.cs, Source/Client/UI/DebugPanel/StatusBadge.cs, Source/Client/UI/DebugPanel/SyncDebugPanel.cs, Source/Client/UI/IngameUI.cs
- Replace the old 'text with no label' debug wall with a newer version thats easier to read.
=> Prettify debug information panel

Source/Client/Factions/Forbiddables.cs
Fix for #574 
> I think I found the cause, but I don't know why it didn't cause this problem before. (RimWorld 1.5)
> All Things were being added to the unforbidden list, whether they were forbidden or not.
> `Forbiddables.cs`
> ```c#
>     [HarmonyPatch(typeof(Thing), nameof(Thing.SpawnSetup))]
>     static class ThingSpawnSetForbidden
>     {
>         static void Prefix(Thing __instance, Map map, bool respawningAfterLoad)
>         {
>             if (respawningAfterLoad) return;
>             if (Multiplayer.Client == null) return;
> 
>             if (ThingContext.stack.Any(p => p.Item1?.def == ThingDefOf.ActiveDropPod)) return;
> 
>             if (__instance is ThingWithComps t && t.GetComp<CompForbiddable>() != null)
> …
```
=> Fix: Starting items not marked as forbidden

Source/Client/AsyncTime/AsyncTimePatches.cs, Source/Client/AsyncTime/TimeControlUI.cs, Source/Client/Debug/DebugPatches.cs, Source/Client/Factions/Blueprints.cs, Source/Client/Factions/MultifactionPatches.cs, Source/Client/Patches/AllGroupsPatch.cs, Source/Client/Patches/ArbiterPatches.cs, Source/Client/Patches/Determinism.cs, Source/Client/Patches/Feedback.cs, Source/Client/Patches/HashCodes.cs, Source/Client/Patches/Patches.cs, Source/Client/Patches/Seeds.cs, Source/Client/Persistent/ISwitchToMap.cs, Source/Client/Persistent/RitualPatches.cs, Source/Client/Persistent/Trading.cs, Source/Client/Syncing/Game/SyncMethods.cs, Source/Client/Windows/ModCompatWindow.cs
Feel free to reject, but the warnings are triggering me.  This PR resolves 41 compiler warnings.
[CS0252](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0252) warns:
> warning CS0252: Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'type'
Basically we could inadvertently be doing reference checks instead of value checks. The compiler suggests casting to a concrete class (since most of these are generic `object`s).  But that introduces new risks, and complicates the checks. Switching to using `.Equals` on the known concrete class will, at worst do the same reference check, and at best do an value check.  Plus it has the added bonus of clearing the compiler warnings.
I plan to resolve a bunch more warnings, but I figured splitting …
=> Resolve reference comparison warnings (CS0252)

Source/.editorconfig
This resolves 4 compiler warnings.
Based off [this comment](https://github.com/rwmt/Multiplayer/pull/577#issuecomment-3089864522), CS0436 looks like this:
> `\Source\Common\Util\Endpoints.cs(10,66)`: warning CS0436: The type `NotNullWhenAttribute` in `\Source\Common\Util\CompilerTypes.cs` conflicts with the imported type `NotNullWhenAttribute` in `mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`. Using the type defined in `\Source\Common\Util\CompilerTypes.cs`.
Basically some newer features from .NET Core have been replicated in this codebase to support .NET Framework.  In other languages we'd call this a [polyfill](https://en.wikipedia.org/wiki/Polyfill_(programming)).
It turns out to be harder to disable this in-code than expected, because the compiler warns …
=> Clear warnings about conflicting types

Source/Client/Networking/NetworkingSteam.cs, Source/Client/Networking/State/ClientLoadingState.cs, Source/Client/Windows/ConnectingWindow.cs, Source/Common/ByteReader.cs, Source/Common/Networking/ConnectionBase.cs, Source/Common/Networking/FragmentedPacket.cs, Source/Common/Networking/MpConnectionState.cs, Source/Common/Networking/NetworkingLiteNet.cs, Source/Common/Networking/PacketHandlerAttribute.cs, Source/Common/Version.cs
Implement a more complete system for handling fragmented packets. It supports receiving multiple fragmented packets' parts at once*, and allows handling a fragmented packet's individual parts as they arrive. The latter is used to introduce a lot more information to the world download dialog when connecting to a server. It's previous implementation was bare-bones and mixed networking code with some book-keeping for the dialog. That can now be properly separated and the state is now handled by `ClientLoadingState` which the dialog just interfaces with.
https://github.com/user-attachments/assets/3c2bc3fe-5f85-4c6b-91b0-c1827707df33
In the demo video above, the progress bar jumps around a bit. That's because the fragmented packets can now see the independent parts arriving, but only when they …
=> Extended support for fragmented packets and handling them. Improved download dialog

Source/Client/UI/DebugPanel/PerformanceRecorder.cs, Source/Client/UI/DebugPanel/SyncDebugPanel.cs
This pull request updates the `PerformanceRecorder` class to replace lists with CircularBuffer for improved memory management and performance tracking, along with other misc improvements.
* Replaced lists with `CircularBuffer` for performance metrics, allowing for a rolling window of data.
* Introduced constants `MaxSampleCount` and `NonPerfMetricsFrameInterval` to limit buffer size and non-performance metric sample rate.
* Updated methods for recording metrics to accommodate the new buffer structure.
* Improved logging functionality with warnings for full sample buffers.
=> Performance recorder - Circular buffer, general improvements

Source/Client/Factions/FactionCreator.cs
Label: 1.5, 1.6, Bug, Multifaction
Fixes #585.
Tested on 1.6 (dev) and 1.5 (rw-1.5)
`ScenPart_StartingResearch.PostGameStart` was only executed on the local machine of the faction creator.  
As a result, the host/save did not reflect this change properly.
I’ve opened an issue (#587) to improve the overall handling of ScenParts. I believe there’s more to gain by reviewing the other available scenParts and their methods. I’ve added this as a TODO for future work.
=> Fix scenario research lost on reconnect (#585)

Source/Client/Factions/FactionCreator.cs
Removing obsolete workaround #535 because it is implemented correctly by #575
=> Removing obsolete workaround #535 fixed by #575

Source/Client/AsyncTime/TimeControlUI.cs, Source/Client/Factions/Blueprints.cs, Source/Client/Factions/MultifactionPatches.cs, Source/Client/Patches/AllGroupsPatch.cs, Source/Client/Patches/Determinism.cs, Source/Client/Patches/Patches.cs, Source/Client/Persistent/ISwitchToMap.cs
For 1.6
My PR #576 was flawed. I saw a pattern and ran with it, relying too much on the compiler to catch any errors. My bad.
Thanks to @Tick-git for highlighting the issue.  Many of these `CodeInstruction` operands weren't actually `MethodInfo`.  The problem is that they shared common classes (a lot were `FieldInfo` which extends from `MethodInfo`), so the compiler let it all slide.
I've gone through this _twice_ to ensure I'm casting to the correct classes now.
According to Tick this should resolve #590.
_Note:_ Tick also pointed out that Harmony provides a bunch of [extensions](https://harmony.pardeike.net/api/HarmonyLib.CodeInstructionExtensions.html) for doing these comparisons (for example [`.Calls(MethodInfo method)`](https://harmony.pardeike.net/api/HarmonyLib.CodeInstructionExtens …
=> Fix incorrect class casts

Source/Client/Factions/FactionCreator.cs
Label: 1.6, Bug
That was a bit of a pain one for me - I kept chasing the wrong direction while the real issue was elsewhere. I had a fix early on, but understanding why it happened took a while.  :'( :D
Fixes #591
**Shortform:**
Fixes an issue where pawn textures lingered in  `PortraitsCache` due to `thingID` changes during faction creation in multifaction, causing hash mismatches. This led to errors when accessing stale pawn maps during the update loop - now resolved by clearing the cache post faction creation.
**Longform:**
In multifaction gameplay, when a new faction is created, we use `Page_ConfigureStartingPawns`, which internally calls `PortraitsCache.Get`. The `PortraitsCache` is responsible for caching pawn textures, stored in a `Dictionary<Pawn, Texture>`. These textures are …
=> Clear PortraitsCache post faction creation

Source/Client/Networking/State/ClientPlayingState.cs, Source/Common/ChatCommands.cs, Source/Common/MultiplayerServer.cs, Source/Common/Networking/ConnectionBase.cs, Source/Common/Networking/PacketReadException.cs, Source/Common/Networking/State/ServerPlayingState.cs, Source/Common/ServerPlayer.cs
Each commit is self-contained and small, so grouping them into a single PR seems reasonable.
=> A few internal improvements

Source/Common/Networking/ConnectionBase.cs
The limit should've been 32 MiB but was but accident set too low to 1 KiB
=> Update max packet size validation to use MaxFragmentPacketTotalSize

Source/Client/AsyncTime/AsyncTimeComp.cs, Source/Client/MultiplayerStatic.cs, Source/Client/Patches/Designators.cs, Source/Client/Patches/Plans.cs, Source/Client/Syncing/Dict/SyncDictMisc.cs
- Fixed plan implementation to work when multiple maps are loaded.
=> Fixed plan implementation to work when multiple maps are loaded.

Source/Client/AsyncTime/AsyncTimePatches.cs
Classes that implement IThingHolder are, as of RimWorld 1.6, always included in the normal tick list.
This PR updates our tick system to reflect that change.
Note: Corpses are IThingHolder and are still ticked rarely, but this is now handled directly via Thing.DoTick rather than through the tick list.
Reference: RimWorld 1.6 source code: `TickManager.TickListFor` `Thing.DoTick`
=> Fix: corpses do not rot

Source/Client/MultiplayerStatic.cs
Label: 1.6, Fix, Mulifaction, but might be relevant in normal, too
This commit ensures that Things push their faction before ticking their systems.
This is required due to changes in RimWorld 1.6, where the tick process for things was updated:
- The method TickInterval() was introduced and is now part of the tick flow, so we added a patch for it.
- The method Tick() was changed to protected, so we updated our method search to include non-public methods to ensure proper patching.
=> Fix Multifaction: Pawns Disappear When Caravan To Other Player Map

Source/Client/MultiplayerStatic.cs, Source/Client/Syncing/Dict/SyncDictRimWorld.cs
Label: 1.6, fix
**Commit 2:** 
Fixes an error in syncing process for Action<PlanetTile, TransportersArrivalAction> action) that is used in Transport Pod launches. This has been the main problem in both multifaction/normal play. After this commit, transport pods in normal play work correctly.
**Commit 1:** 
World objects have changed their tick system in 1.6. Therefore, the faction context was not correctly pushed anymore. Same as for things in: #616. This is needed for correct transport pod behaviour in multifaction.
**Desync:** 
When attacking a map with transport pod, more often than not a desync is happening after the pods land on the map. I tested this on 1.5 and there it happens as well. It might happen not in normal mp play and only in multifaction, but have not tested it enough to …
=> Fixes Transport pod exception

Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/Syncing/Game/SyncActions.cs
Label: 1.6, Enhancement
I did test it mainly on one colony play and loosely in multifaction.
Removed code is not necessary, because it can all be synced by CompLaunchable.TryLaunch via SyncMethods.cs. 
This way transport pots and shuttles are synced the same way.
This change leads to some saving warnings in syncing TryLaunch that are harmless and were already present for space shuttles.
=> Refactor: Removes Transport Pod Float Option Syncing

Source/Common/DeferredStackTracingImpl.cs, Source/Common/Native.cs
Label: 1.6, Fix
With the Mono update in 1.6, method names now include additional build- and platform-specific details, which breaks cross-platform consistency.
This PR removes the new Mono 1.6 extra data to restore consistent cross-platform stack trace hashing.
I believe this should fix all cross-OS play. It has been tested on Linux/Windows.
**Desync file example below for #621 in 1.5 and 1.6** 
In Mono 1.5, stack traces included a postfix like `<0xffffffff>`.
In Mono 1.6, the format changed to `[0x00025] in <b994eb69d2df47fdb01add71b9ac29d2>:0.`
This extra data maps the method to a specific assembly and changes with each build.
Because RimWorld assemblies differ between Linux and Windows, these values also differ between platforms, causing desync issues.
=> Fix Cross OS Play Immediate Desync

Source/Client/Debug/DebugSync.cs, Source/Client/Multiplayer.cs, Source/Client/MultiplayerAPIBridge.cs, Source/Client/MultiplayerGame.cs, Source/Client/Saving/CrossRefs.cs, Source/Client/Saving/ThingsById.cs, Source/Client/Session/PlayerInfo.cs, Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/UI/CursorPatches.cs
Label: 1.6, 1.5, Fix
The error in this PR probably didn’t occur often before, but with gravship it will happen more frequently since maps are generated and abandoned often. I also encountered this in #581, but couldn’t reproduce it at the time.
The static data causes problems when two saves are played in one process.
`public static Dictionary<int, Thing> thingsById = new();`
In the first game, many maps are used, therefore some static cached things have a high mapIndex.
In the next game, fewer maps are used and one map is abandoned.
The static data from save before is not cleared correctly, and when map gets abandoned:
```
public class ThingsById
public void UnregisterAllFrom(Map map)
{
thingsById.RemoveAll(kv => kv.Value.Map == map);
}
```
calls a map getter that uses Find.Maps and tries …
=> Refactor ThingsById system to use non static data

Source/Client/AsyncTime/AsyncWorldTimeComp.cs, Source/Client/Comp/Map/MultiplayerMapComp.cs, Source/Client/Patches/Feedback.cs, Source/Client/Patches/GravshipTravelSessionPatches.cs, Source/Client/Patches/VTRSyncPatch.cs, Source/Client/Persistent/GravshipTravelSession.cs, Source/Client/Syncing/Dict/SyncDictRimWorld.cs, Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Game/SyncMethods.cs
**Label:** 1.6 Odyssey
This is a polished version of @Reznal’s SPACESHIP branch.
**This PR introduces the following gravship behaviors:**
* Flying to new maps, anchors, and asteroids
* Attacking NPC settlements and space stations
**Known issues:**
* The gravship in multi-faction mode doesn’t currently work and hasn’t been tested
* Aborting a landing can sometimes select a different map, which causes a desync
There are still some parts to refactor. This should be seen as a first iteration, intended to make collaboration easier.
=> Gravship Basic Behavior

Source/Client/ConstantTicker.cs, Source/Client/Patches/Determinism.cs, Source/Client/Syncing/Game/SyncDelegates.cs, Source/Common/FreezeManager.cs
I've replaced a few of the constant values (that I could catch) used in the mod with references to the in-game constants.
I've done this primarily to make the intentions behind those values clearer. Using `GenTicks.TicksPerRealSecond` is more obvious that the value refers to amount of ticks in a second, rather than just using the value of `60`. Likewise, using `GenDate.TicksPerDay` is much easier to understand than a value of `60000` or `2500 * 24`.
The only "change" on top is changing `1 / 60f` to `1f / GenTicks.TicksPerRealSecond` (`1` to `1f`), as we need one of those values to be a float (or we'll end up with integer division).
This will not change anything gameplay-wise, as all those constants will be computed at compile time and end up the same in the compiled code. This will only …
=> Use built-in constants for tick values

Source/Client/AsyncTime/AsyncTimePatches.cs
`TickManagerPausedPatch` was not running in MP if `WorldRendererUtility.WorldRendered` is true. However, we wanted to use `WorldRendererUtility.WorldSelected`, as the former checks if the world is rendered at all (including as a background for space maps), while the latter checks if the world is rendered due to the player opening the world map.
There's several bugs that could happen due to this:
- Camera shaker running while paused
- Normally `CameraShaker:ShakeOffset` returns `Vector3.zero` while paused
- Audio samples being paused while the game is running, not pausing while the game is paused, or having incorrect pitch/volume
- `FleckMaker:ThrowMetaPuffs` creating flecks while paused
- This method normally only does it while unpaused
- Possibly more in vanilla, and likely a lot more …
=> Fix space maps being incorrectly considered paused/unpaused in certain circumstances

Source/Client/Factions/MultifactionPatches.cs
In 1.5, this used to be a check for colony mutant, and included Anomaly check since base game did so as well.
In 1.6, the code we patched was replaced to not be a mutant check, but a subhuman check. This check doesn't include a check for Anomaly DLC, so I've removed it to match base game behavior.
=> Remove anomaly check from colony subhuman check

Source/Client/Patches/Seeds.cs
`PreceptComp_UnwillingToDo_Chance:MemberWillingToDo` uses RNG, which may be called in interface or other places that cause issues.
In vanilla, this only affects "marriage name" issue, specifically when set to "usually man's" or "usually woman's" (when playing without Ideology, it uses the former).
I've seeded the method using the pawn's ID (if present, using `Find.World.ConstantRandSeed` as fallback) combined with the current tick to ensure results are unique for each pawn, but will always be the same on a given tick. The fallback is mostly a precaution, as this precept comp is expecting a pawn.
This should fix desyncs that are sometimes caused due this precept comp.
This could probably be handled in a smarter way, so if anyone has an idea on how and is willing to do it - go ahead make it …
=> Fix desyncs due to `PreceptComp_UnwillingToDo_Chance`

Source/Client/Patches/VTRSyncPatch.cs
Just like a gravship, travelling transporters (drop pods, shuttles) calculate their position in tick interval (once every 15 ticks if VTR is active). Since we always assume VTR is active on the world (besides gravships), this means they won't be moving too smoothly. I've set their update rate to always be 1 to fix this issue, just like with gravships.
On top of that, I've rearranged the code into if/else branches to make sure we only assign the result once, instead of potentially twice.
=> Make world's travelling transporters smoother

Source/Client/AsyncTime/AsyncTimePatches.cs, Source/Client/AsyncTime/SetMapTime.cs
When playing MP 1.5 with AsyncTime I noticed pawns with chemical dependencies were misreporting their last ingest times based on what map they were in. 
After some admittedly quick digging through the async time patches I devised 2 new patches that are specifically targeted at this one issue.  
However I believe this type of issue to exist elsewhere for AsyncTime games.  But I lack a solid way of reproducing different instances of this kind of issue.  For instance, Rimworld's code calls `TickManager.TicksGame` in the "Deathrest Gene" as well.  I recall seeing a shield recharge time count with an absurd value once too, but don't know how to reproduce this.
All things considered my MP knowledge is too limited to know if there may be a more concise and universal fix for this class of async …
=> Patch TickManager for Chemical Dependency Gene

Source/Client/Patches/GravshipTravelSessionPatches.cs, Source/Client/Persistent/GravshipTravelSession.cs, Source/Client/Syncing/Game/SyncDelegates.cs, Source/Client/Syncing/Game/SyncMethods.cs
Label: 1.6, Fix, Odyssey
Launching a gravship from an anchored map failed to create the session correctly when the world tile picker is selected.
This bug was introduced by my recent refactor of GravshipTravelSessionPatches.cs.
The fix updates how preconfirm dialog options are synced, removing the need to sync `StartChoosingDestination_NewTemp`, where the postfix and `!Multiplayer.ExecutingCmds` check caused the issue.
Additionally, removed some code that was needed because the method was synced.
=> Fix Gravship Launch Anchored Map Session Creation

Source/Client/Patches/Feedback.cs, Source/Client/Syncing/Game/SyncMethods.cs
We're syncing anything in the vanilla assembly implementing the `ITargetingSource:OrderForceTarget` method (with exception of `CompInteractableRocketswarmLauncher`).
This causes issues with `CompUsable`, since the execution of its `OrderForceTarget` method can be cancelled and instead another targeter opened (if the thing also has `CompTargetable` whose `PlayerChoosesTarget` property returns true).
In multiplayer, this causes an issue where targeter is opened for all players, and on top of that since the caster pawn is selected from that method it could end up being overwritten by a different caster or null.
This should fix the issues related to such situations. This means that it'll fix sentience catalyst, resurrector serums, as well as other things. This may potentially fix #655, …
=> Fix syncing of CompUsable that trigger another targetter

Source/Client/Comp/Map/FactionMapData.cs, Source/Client/Comp/Map/MultiplayerMapComp.cs
Added `PlanManager` to `FactionMapData`, initialized it, and exposed. It'll also be applied from `SetFaction` call.
I'll be honest, I expected this to need much more work than it actually was? Everything seems to be handled due to the faction being set properly where it needs to be set. Everything seems to work fine on my end.
Unrelated to this PR, but we may need to double-check the plan renaming feature since it seems to cause a double write/read.
=> Make plans faction-based

Source/Client/Comp/Map/FactionMapData.cs, Source/Client/Comp/World/FactionWorldData.cs
#670 was causing errors due to the `planManager` field being null when exposing data, so to fix it I've made sure it's created if null.
However, I've decided to initialize all relevant map/world faction fields if null for all factions in case of any weird errors or issues.
=> Extra null safety for faction data, fix errors with #670

Source/Client/Debug/DebugActions.cs, Source/Client/Debug/DebugSync.cs, Source/Client/Desyncs/ClientSyncOpinion.cs, Source/Client/Desyncs/LogGenerator.cs, Source/Client/Desyncs/MapRandomStateData.cs, Source/Client/Desyncs/MetadataGenerator.cs, Source/Client/Desyncs/SaveableDesyncInfo.cs, Source/Client/Desyncs/StackTraceLogItem.cs, Source/Client/Desyncs/SyncCoordinator.cs, Source/Client/Multiplayer.csproj, Source/Client/Util/CollectionExtensions.cs, Source/Client/Util/HarmonyUtil.cs, Source/Client/Windows/DesyncedWindow.cs, Source/MultiplayerLoader/MultiplayerLoader.cs
This adds a debug action to trigger a desync, improves desync generation by: making it faster, on my system it takes ~0.9s, where as before it took ~1.8s; the game no longer freezes when saving the desync report (saving now takes ~50ms, because the slowest code is run in the background - metadata generation); added a new file to the desync report with just the metadata (mods, patches, harmony versions).
=> Trigger desync debug action, faster desync report generation, and separated metadata in the report

Source/Client/Networking/State/ClientBaseState.cs, Source/Client/Networking/State/ClientLoadingState.cs, Source/Client/Networking/State/ClientPlayingState.cs, Source/Client/OnMainThread.cs, Source/Common/MultiplayerServer.cs, Source/Common/Networking/State/ServerPlayingState.cs
When a client is joining a server, the server sends a lot of packets during client loading that aren't properly handled (or shouldn't actually be sent). Now, the Server_Cursor packet is only sent to players that are already loaded (as it doesn't make sense to send it to players that are loading), and Server_KeepAlive and Server_TimeControl are now handled by the client during loading time too.
=> Improve handling of packets when loading

Source/Common/Networking/AsyncConnectionState.cs, Source/Common/Networking/MpConnectionState.cs, Source/Common/Networking/PacketHandlerAttribute.cs
Now the invoker's signature is actually truthful and the code to generate a delegate for it is more straightforward than with the MethodInvoker.
=> Use dedicated PacketHandlerInvoker delegate for handling packets

.github/workflows/alpha-notes.md, .github/workflows/build-beta.yml
You can see a demo at: https://github.com/mibac138/Rimworld-Multiplayer/releases/tag/continuous
=> Add installation instructions to the continuous release

Source/Client/UI/DebugPanel/SyncDebugPanel.cs
=> Fix the SyncDebugPanel having content cut off

Source/Client/Multiplayer.cs, Source/Client/Patches/VTRSyncPatch.cs, Source/Common/Networking/State/ServerPlayingState.cs, Source/Common/PlayerManager.cs, Source/Common/ServerPlayer.cs
=> Fix VTRSync player count tracking

Source/Client/UI/IngameDebug.cs
=> DebugModeLabel: fix cut off text when Disable tiny font is enabled

Source/Client/Patches/VTRSyncPatch.cs, Source/Common/Networking/State/ServerPlayingState.cs, Source/Common/PlayerManager.cs, Source/Common/ServerPlayer.cs
Lowest hanging fruit from #710
=> VTRSync: mapIndex -> mapId

Source/Client/Multiplayer.cs, Source/Client/UI/DebugPanel/PerformanceRecorder.cs
The MpLogs directory was not created automatically anywhere, which
caused an exception that the file could not be saved.
=> PerformanceRecorder: fix saving exception

Source/Client/Util/VersionChecker.cs
When git hash ends with dirty, it means that some files were modified during compilation and the changes weren't committed. Release artifacts are not supposed to be dirty, so this hides the dialog only during local development (even if running in release mode).
=> VersionChecker: ignore dirty Git hashes for continuous releases

Source/Client/UI/DebugPanel/SyncDebugPanel.cs, Source/Client/Util/RectExtensions.cs
The increased spacing between entries is a side effect of the height calculation.
Before:
After:
=> SyncDebugPanel: fix text clipping when tiny font is disabled

Source/Client/Settings/MpSettingsUI.cs, Source/Client/Util/FileAssoc.cs
Introduces a .rwmts extension for the assocation. Currently unused by Multiplayer itself - only created manually.
=> Add experimental debug-only file association for Multiplayer saves

Source/Client/Persistent/SessionManager.cs
I have found at least one cause of this - an ExposableSession without a constructor with a single Map parameter. There might be other causes.
Reported [here](https://discord.com/channels/524286515644203028/1071408557314035852/1419257105046700135) and present in the logs of this [report](https://discord.com/channels/524286515644203028/1420952075587686553/1420952075587686553) (this fix isn't the root cause of that report).
Exposable sessions that do not expose a valid constructor:
- CaravanFormingSession
- TransporterLoading
Additionally, while the exposable session CaravanSplittingSession does have the required constructor, it fails to load. That's because caravan splitting is a world-session, not a map session, so the Map argument used in this method call: `Scribe_Collections.Look(ref …
=> Fix PostLoadInit NullReferenceException

Source/Client/Persistent/CaravanFormingSession.cs, Source/Client/Persistent/CaravanSplittingPatches.cs, Source/Client/Persistent/CaravanSplittingSession.cs, Source/Client/Persistent/MapPortalSession.cs, Source/Client/Persistent/SessionManager.cs, Source/Client/Persistent/TransporterLoadingSession.cs, Source/Client/Syncing/ApiSerialization.cs
Now all ExposableSessions can survive a save-load cycle.
Related: #724
=> Verify sessions are valid on startup

Source/Client/AsyncTime/AsyncTimeComp.cs, Source/Client/AsyncTime/AsyncWorldTimeComp.cs, Source/Client/Networking/HostUtil.cs, Source/Client/Networking/State/ClientPlayingState.cs, Source/Client/Util/Extensions.cs, Source/Common/CommandHandler.cs, Source/Common/ScheduledCommand.cs
The server has been sending command packets with `issuedBySelf` info since e52de8d866e992d42b3d28c73b7ea44f60132d86 (2018) when the responsible class was `MultiplayerServer`. About half a year later the client has gained knowledge about their own id in af1928e2d9749bf13d12cfe2aef4f380d5545807. With that change the client can now determine on it's own whether a given command was issued by itself, making the `issuedBySelf` field redundant.
=> ScheduledCommand: client-side issuedBySelf

Source/Common/DeferredStackTracingImpl.cs
In case the detection fails, fallback to the previous value of 1 long as the previous code used + 1 to actually mean 8 bytes. If something does go wrong with the detection, dump the code of the whole method to help debug.
Needs more testing to make sure it works correctly across different machines.
Tested with the save file from https://github.com/rwmt/Multiplayer/issues/658#issuecomment-3240114885
Related: #562, #662
=> Dynamically detect rbp offset used in GetRbp

Source/Client/EarlyPatches/SettingsPatches.cs
Previously it was possible to circumvent this:
- join a Multiplayer game,
- go to options and click Development mode
- this causes a call to Prefs.Apply -> PrefsData.Apply, which updates runInBackground from it's own field instead of our patched value.
=> Make sure to always run in background during Multiplayer game
